function d = sensorDomain(key)
%sensorDomain  Descriptor for a sensor-modality domain (radar | sonar | ir).
%
%   d = trackbench.editor.sensorDomain(key)
%
%   Author:  Team Adeptus - UW Senior Capstone, Boeing-sponsored
%   Since:   v3.7.x (modality-domain Phase 1; see design/ADR-001-modality-domains.md)
%
%   ONE source of truth for everything that varies by sensor modality in the
%   Path Editor. The editor and launch flow read fields off this struct
%   instead of scattering `if isSonar ...` checks. Adding a domain or
%   changing a palette happens here, in one place.
%
%   FIELDS
%     key            "radar" | "sonar" | "ir"
%     label          human label for the picker
%     sensorTypes    cellstr palette (the buildSensor type keys this domain offers)
%     defaultSensor  the type a fresh scenario starts with
%     vertical       struct(label, zdir, sign) - vertical-axis framing
%                      zdir : axes ZDir ("normal" up / "reverse" down)
%                      sign : +1 if the editor's z grows downward (depth), else -1
%     environment    default environment family ("terrain" | "none")
%     defaultTerrain editor terrain default for the domain
%     defaultTracker run-config tracker for the domain (TYPE/name)
%     resultView     "standard" (radar theaterPlot) | "plotByModality"
%     targetHint     label for the default target kind
%
%   See also: trackbench.editor.sensorDefaults, pathEditor,
%             trackbench.reporting.plotByModality

    if nargin < 1 || isempty(key); key = "radar"; end
    key = lower(string(key));

    switch key
        case "radar"
            d = struct( ...
                'key',           "radar", ...
                'label',         "ATC Radar", ...
                'sensorTypes',   {{'PSR','SSR','ASR','ARSR','PAR','MARITIME','WEATHER','TWS'}}, ...
                'defaultSensor', "PSR", ...
                'defaultVerticalM', 3000, ...
                'vertical',      struct('label',"Altitude (m)",'zdir',"normal",'sign',-1), ...
                'environment',   "terrain", ...
                'defaultTerrain',"rural", ...
                'defaultTracker',"GNN/default_GNN", ...
                'resultView',    "standard", ...
                'targetHint',    "aircraft");

        case "sonar"
            d = struct( ...
                'key',           "sonar", ...
                'label',         "Maritime Sonar", ...
                'sensorTypes',   {{'ACTIVE_SONAR','PASSIVE_SONAR','TOWED_ARRAY'}}, ...
                'defaultSensor', "ACTIVE_SONAR", ...
                'defaultVerticalM', 300, ...
                'vertical',      struct('label',"Depth (m, +down)",'zdir',"reverse",'sign',+1), ...
                'environment',   "none", ...
                'defaultTerrain',"none", ...
                'defaultTracker',"GNN/sonar_GNN", ...
                'resultView',    "plotByModality", ...
                'targetHint',    "submarine");

        case "ir"
            d = struct( ...
                'key',           "ir", ...
                'label',         "Passive IR / IRST", ...
                'sensorTypes',   {{'IRST','IR_STARING','FLIR'}}, ...
                'defaultSensor', "IRST", ...
                'defaultVerticalM', 3000, ...
                'vertical',      struct('label',"Altitude (m)",'zdir',"normal",'sign',-1), ...
                'environment',   "none", ...
                'defaultTerrain',"none", ...
                'defaultTracker',"GNN/test_IRST_GNN", ...
                'resultView',    "plotByModality", ...
                'targetHint',    "aircraft");

        otherwise
            error('trackbench:editor:sensorDomain:badKey', ...
                'Unknown domain "%s". Use one of: radar | sonar | ir.', key);
    end
end
