function tracker = buildTracker(trackerType, filterModel, params, globalParams, filterParams, pd, numSensors)
% BUILDTRACKER Factory function to create configured tracker objects
% Maps JSON parameters to the specific property names required by GNN/TOMHT/JPDA.
%
% CHANGE LOG
%   - Added HasDetectableTrackIDsInput = true for GNN and JPDA.
%     This tells the tracker which tracks were actually observable (in FOV)
%     each scan. Tracks outside the sensor FOV are excluded from track logic,
%     so their score doesn't drop and they won't be falsely deleted during
%     beam gaps. The detectable IDs are computed in helperRunTracker using
%     the sensor configs stored in dataLog.SensorConfig.
%   - Added MaxNumEvents=100 to JPDA to prevent combinatorial explosion
%     when many clutter detections fall in overlapping gates.

    % Optional arg: number of unique sensors expected in the detection stream.
    % If detections contain SensorIndex values > 1, the tracker MUST be told
    % how many sensors to expect via MaxNumSensors.
    if nargin < 7 || isempty(numSensors)
        numSensors = 1;
    end
    numSensors = max(1, double(numSensors));

    % Wrap the filter initialization function to bake in the config parameters.
    % The tracker expects a function that only takes `det`.
    if strcmpi(filterModel, 'CV')
        initFcn = @(det) trackbench.tracking.initCVFilter(det, filterParams);
    elseif strcmpi(filterModel, 'IMM')
        initFcn = @(det) trackbench.tracking.initIMMFilter(det, filterParams);
    else
        error('[TRACKER] Unknown filter model: %s. Use CV or IMM.', filterModel);
    end

    % Build the specific tracker type using the mapped parameters
    switch upper(trackerType)
        case 'GNN'
            tracker = trackerGNN( ...
                'FilterInitializationFcn', initFcn, ...
                'MaxNumTracks', globalParams.max_num_tracks, ...
                'MaxNumSensors', numSensors, ...
                'AssignmentThreshold', params.gate, ...
                'TrackLogic', 'Score', ...
                'DetectionProbability', pd, ...
                'FalseAlarmRate', params.far_gnn, ...
                'Volume', globalParams.volume, ...
                'Beta', globalParams.beta, ...
                'HasDetectableTrackIDsInput', true);
            % HasDetectableTrackIDsInput: tracker will accept a 3rd argument
            % (detectableTrackIDs) in each call. Track logic (score update,
            % deletion) is only evaluated for tracks in that list. Tracks
            % outside the FOV coast on Kalman prediction without penalty.

        case 'TOMHT'
            tomhtThresh = params.tomht_threshold_multiplier * params.gate;
            tracker = trackerTOMHT( ...
                'FilterInitializationFcn', initFcn, ...
                'MaxNumTracks', globalParams.max_num_tracks, ...
                'MaxNumSensors', numSensors, ...
                'AssignmentThreshold', tomhtThresh, ...
                'DetectionProbability', pd, ...
                'FalseAlarmRate', params.far_mht, ...
                'Volume', globalParams.volume, ...
                'Beta', globalParams.beta, ...
                'ConfirmationThreshold', params.confirm_threshold, ...
                'DeletionThreshold', params.delete_threshold, ...
                'MaxNumHistoryScans', 10, ...
                'MaxNumTrackBranches', params.max_branches, ...
                'NScanPruning', 'Hypothesis', ...
                'OutputRepresentation', 'Tracks');
            % NOTE: trackerTOMHT does not support HasDetectableTrackIDsInput.
            % TOMHT manages hypotheses internally and is more naturally robust
            % to missed detections via its n-scan pruning logic.

        case 'JPDA'
            tracker = trackerJPDA( ...
                'FilterInitializationFcn', initFcn, ...
                'MaxNumTracks', params.num_tracks_jpda, ...
                'MaxNumSensors', numSensors, ...
                'AssignmentThreshold', params.gate_jpda, ...
                'TrackLogic', 'Integrated', ...
                'DetectionProbability', pd, ...
                'ClutterDensity', params.far_jpda / globalParams.volume, ...
                'NewTargetDensity', params.beta_jpda, ...
                'TimeTolerance', params.time_tolerance_jpda, ...
                'MaxNumEvents', 100, ...
                'HasDetectableTrackIDsInput', true);
            % MaxNumEvents=100: prevents combinatorial explosion when many
            % clutter detections fall in overlapping gates. Without this,
            % JPDA tries to enumerate 2^N events and crashes with OOM.
            % HasDetectableTrackIDsInput: same benefit as GNN.

        otherwise
            error('[TRACKER] Unknown tracker type: %s', trackerType);
    end
end