function tracker = buildTracker(trackerType, filterModel, params, globalParams, filterParams, pd, numSensors)
% BUILDTRACKER Factory function to create configured tracker objects.
%
%  Maps JSON parameters to the specific property names required by
%  trackerGNN, trackerTOMHT, and trackerJPDA.
%
%  REFERENCES
%    [1] MathWorks, trackerGNN documentation:
%        https://www.mathworks.com/help/fusion/ref/trackergnn-system-object.html
%    [2] MathWorks, trackerJPDA documentation:
%        https://www.mathworks.com/help/fusion/ref/trackerjpda-system-object.html
%    [3] MathWorks, trackerTOMHT documentation:
%        https://www.mathworks.com/help/fusion/ref/trackertomht-system-object.html
%    [4] MathWorks, "Introduction to Track Logic":
%        https://www.mathworks.com/help/fusion/ug/introduction-to-track-logic.html
%    [5] MathWorks, "Introduction to Using the GNN Tracker":
%        https://www.mathworks.com/help/fusion/ug/introduction-to-using-the-global-nearest-neighbor-tracker.html

    if nargin < 7 || isempty(numSensors)
        numSensors = 1;
    end
    numSensors = max(1, double(numSensors));

    % Wrap filter initialization to bake in config parameters.
    if strcmpi(filterModel, 'CV')
        initFcn = @(det) trackbench.tracking.initCVFilter(det, filterParams);
    elseif strcmpi(filterModel, 'IMM')
        initFcn = @(det) trackbench.tracking.initIMMFilter(det, filterParams);
    else
        error('[TRACKER] Unknown filter model: %s. Use CV or IMM.', filterModel);
    end

    % Extract confirm/delete thresholds with defaults
    % These control when tentative tracks become confirmed and when
    % stale tracks are deleted. [4]
    %   Score logic (GNN/TOMHT): scalar thresholds on log-likelihood score
    %   Integrated logic (JPDA): probability-based confirmation
    confirmThresh = 20;   % MathWorks default for Score logic [5]
    deleteThresh  = -7;   % MathWorks default for Score logic [5]
    if isfield(params, 'confirm_threshold')
        confirmThresh = params.confirm_threshold;
    end
    if isfield(params, 'delete_threshold')
        deleteThresh = params.delete_threshold;
    end

    switch upper(trackerType)
        case 'GNN'
            % trackerGNN with Score-based track logic [1][4]
            % AssignmentThreshold: Mahalanobis distance gate for association
            % ConfirmationThreshold: score needed to confirm a tentative track
            % DeletionThreshold: score drop from max before track is deleted
            tracker = trackerGNN( ...
                'FilterInitializationFcn', initFcn, ...
                'MaxNumTracks', globalParams.max_num_tracks, ...
                'MaxNumSensors', numSensors, ...
                'AssignmentThreshold', params.gate, ...
                'TrackLogic', 'Score', ...
                'ConfirmationThreshold', confirmThresh, ...
                'DeletionThreshold', deleteThresh, ...
                'DetectionProbability', pd, ...
                'FalseAlarmRate', params.far_gnn, ...
                'Volume', globalParams.volume, ...
                'Beta', globalParams.beta, ...
                'HasDetectableTrackIDsInput', true);

        case 'TOMHT'
            tomhtThresh = params.tomht_threshold_multiplier * params.gate;
            tracker = trackerTOMHT( ...
                'FilterInitializationFcn', initFcn, ...
                'MaxNumTracks', globalParams.max_num_tracks, ...
                'MaxNumSensors', numSensors, ...
                'AssignmentThreshold', tomhtThresh, ...
                'DetectionProbability', pd, ...
                'FalseAlarmRate', params.far_mht, ...
                'Volume', globalParams.volume, ...
                'Beta', globalParams.beta, ...
                'ConfirmationThreshold', confirmThresh, ...
                'DeletionThreshold', deleteThresh, ...
                'MaxNumHistoryScans', 10, ...
                'MaxNumTrackBranches', params.max_branches, ...
                'NScanPruning', 'Hypothesis', ...
                'OutputRepresentation', 'Tracks');

        case 'JPDA'
            % trackerJPDA with Integrated track logic [2]
            % Integrated logic uses probability of existence, not score.
            % ConfirmationThreshold/DeletionThreshold are probability values
            % in [0,1] for Integrated logic. Default: confirm at 0.95, delete at 0.1.
            % We map our score-based thresholds to probabilities.
            jpda_confirm = 0.95;  % high confidence to confirm
            jpda_delete  = 0.05;  % low confidence to delete
            if isfield(params, 'jpda_confirm_prob')
                jpda_confirm = params.jpda_confirm_prob;
            end
            if isfield(params, 'jpda_delete_prob')
                jpda_delete = params.jpda_delete_prob;
            end

            tracker = trackerJPDA( ...
                'FilterInitializationFcn', initFcn, ...
                'MaxNumTracks', params.num_tracks_jpda, ...
                'MaxNumSensors', numSensors, ...
                'AssignmentThreshold', params.gate_jpda, ...
                'TrackLogic', 'Integrated', ...
                'ConfirmationThreshold', jpda_confirm, ...
                'DeletionThreshold', jpda_delete, ...
                'DetectionProbability', pd, ...
                'ClutterDensity', params.far_jpda / globalParams.volume, ...
                'NewTargetDensity', params.beta_jpda, ...
                'TimeTolerance', params.time_tolerance_jpda, ...
                'MaxNumEvents', 100, ...
                'HasDetectableTrackIDsInput', true);

        otherwise
            error('[TRACKER] Unknown tracker type: %s', trackerType);
    end
end