function tracker = buildTracker(trackerType, filterModel, params, globalParams, filterParams, pd)
% BUILDTRACKER Factory function to create configured tracker objects
% Maps JSON parameters to the specific property names required by GNN/TOMHT/JPDA.

    % 1. The Fix: Wrap the filter initialization function to bake in the config parameters.
    % Now the tracker sees a function that only takes `det`, keeping MATLAB happy!
    if strcmpi(filterModel, 'CV')
        initFcn = @(det) initCVFilter(det, filterParams);
    elseif strcmpi(filterModel, 'IMM')
        initFcn = @(det) initIMMFilter(det, filterParams);
    else
        error('[TRACKER] Unknown filter model: %s. Use CV or IMM.', filterModel);
    end

    % 2. Build the specific tracker type using the mapped parameters
    switch upper(trackerType)
        case 'GNN'
            tracker = trackerGNN( ...
                'FilterInitializationFcn', initFcn, ...
                'MaxNumTracks', globalParams.max_num_tracks, ...
                'MaxNumSensors', 1, ...
                'AssignmentThreshold', params.gate, ...
                'TrackLogic', 'Score', ...
                'DetectionProbability', pd, ...
                'FalseAlarmRate', params.far_gnn, ...
                'Volume', globalParams.volume, ...
                'Beta', globalParams.beta);
                
        case 'TOMHT'
            tomhtThresh = params.tomht_threshold_multiplier * params.gate;
            tracker = trackerTOMHT( ...
                'FilterInitializationFcn', initFcn, ...
                'MaxNumTracks', globalParams.max_num_tracks, ...
                'MaxNumSensors', 1, ...
                'AssignmentThreshold', tomhtThresh, ...
                'DetectionProbability', pd, ...
                'FalseAlarmRate', params.far_mht, ...
                'Volume', globalParams.volume, ...
                'Beta', globalParams.beta, ...
                'ConfirmationThreshold', params.confirm_threshold, ...
                'DeletionThreshold', params.delete_threshold, ...
                'MaxNumHistoryScans', 10, ...
                'MaxNumTrackBranches', params.max_branches, ...
                'NScanPruning', 'Hypothesis', ...
                'OutputRepresentation', 'Tracks');
                
        case 'JPDA'
            tracker = trackerJPDA( ...
                'FilterInitializationFcn', initFcn, ...
                'MaxNumTracks', params.num_tracks_jpda, ...
                'MaxNumSensors', 1, ...
                'AssignmentThreshold', params.gate_jpda, ...
                'TrackLogic', 'Integrated', ...
                'DetectionProbability', pd, ...
                'ClutterDensity', params.far_jpda / globalParams.volume, ...
                'NewTargetDensity', params.beta_jpda, ...
                'TimeTolerance', params.time_tolerance_jpda);
                
        otherwise
            error('[TRACKER] Unknown tracker type: %s', trackerType);
    end
end