%% addDemoScenarios.m — Add demo_ideal and demo_degraded to scenario catalog
% Run from adeptus-rainyday-tracking root:
%   run('scripts/addDemoScenarios.m')
%
% Creates two scenarios with IDENTICAL targets and sensors (PSR + PAR):
%   demo_ideal    — clean environment, no effects → trackers should hold
%   demo_degraded — horizon masking + ground clutter + VCP propagation → swaps expected
%
% The ONLY difference is the environment. Same crossing geometry, same sensors.
% This directly demonstrates the simulation's value: environment degrades tracking.

root = fileparts(fileparts(mfilename('fullpath')));
catPath = fullfile(root, 'config', 'scenarios', 'scenario_catalog.json');
fprintf('Patching: %s\n', catPath);
txt = fileread(catPath);

% Check if already added
if contains(txt, '"demo_ideal"')
    fprintf('demo_ideal already exists. Skipping.\n');
else
    % Insert before the closing "}" of the scenarios object
    % Find the last scenario's closing brace + the outer closing braces
    
    newScenarios = [
    ',' newline newline ...
    '    "demo_ideal": {' newline ...
    '      "description": "DEMO: PSR+PAR, 3 crossing targets, clean environment — baseline for comparison",' newline ...
    '      "sensor_config": "sensors_demo",' newline ...
    '      "overrides": {' newline ...
    '        "scenario.duration_s": 80,' newline ...
    '        "scenario.num_targets": 3,' newline ...
    '        "degradation.enabled": false,' newline ...
    '        "data_logging.use_saved_datalog": false,' newline ...
    '        "data_logging.datalog_file": "cache/demo_ideal.mat",' newline ...
    '        "tracker_params.ideal.gate": 80,' newline ...
    '        "environment.horizon_masking": false,' newline ...
    '        "environment.ground_clutter": false,' newline ...
    '        "environment.propagation_model": false,' newline ...
    '        "environment.terrain_type": "rural",' newline ...
    '        "environment.clutter_density": 0' newline ...
    '      },' newline ...
    '      "targets": [' newline ...
    '        {' newline ...
    '          "behavior": "crossing",' newline ...
    '          "speed_kmh": 850,' newline ...
    '          "start_pos": [-25000, -35000, -4000],' newline ...
    '          "end_pos": [25000, -35000, -4000],' newline ...
    '          "altitude_m": 4000,' newline ...
    '          "_note": "West to east, crosses T2 at (0,-35000) at t~40s"' newline ...
    '        },' newline ...
    '        {' newline ...
    '          "behavior": "crossing",' newline ...
    '          "speed_kmh": 800,' newline ...
    '          "start_pos": [0, -50000, -4000],' newline ...
    '          "end_pos": [0, -20000, -4000],' newline ...
    '          "altitude_m": 4000,' newline ...
    '          "_note": "South to north, SAME ALTITUDE as T1, co-located at t~40s"' newline ...
    '        },' newline ...
    '        {' newline ...
    '          "behavior": "s_maneuver",' newline ...
    '          "speed_kmh": 800,' newline ...
    '          "start_pos": [-8000, -30000, -4000],' newline ...
    '          "turn_rate_dps": 2,' newline ...
    '          "altitude_m": 4000,' newline ...
    '          "_note": "S-maneuver near crossing zone, adds data association ambiguity"' newline ...
    '        }' newline ...
    '      ]' newline ...
    '    },' newline newline ...
    '    "demo_degraded": {' newline ...
    '      "description": "DEMO: PSR+PAR, same 3 targets, environment ON — shows degradation causes track swaps",' newline ...
    '      "sensor_config": "sensors_demo",' newline ...
    '      "overrides": {' newline ...
    '        "scenario.duration_s": 80,' newline ...
    '        "scenario.num_targets": 3,' newline ...
    '        "degradation.enabled": false,' newline ...
    '        "data_logging.use_saved_datalog": false,' newline ...
    '        "data_logging.datalog_file": "cache/demo_degraded.mat",' newline ...
    '        "tracker_params.ideal.gate": 80,' newline ...
    '        "environment.horizon_masking": true,' newline ...
    '        "environment.ground_clutter": true,' newline ...
    '        "environment.propagation_model": true,' newline ...
    '        "environment.terrain_type": "rural",' newline ...
    '        "environment.clutter_density": 0.7' newline ...
    '      },' newline ...
    '      "targets": [' newline ...
    '        {' newline ...
    '          "behavior": "crossing",' newline ...
    '          "speed_kmh": 850,' newline ...
    '          "start_pos": [-25000, -35000, -4000],' newline ...
    '          "end_pos": [25000, -35000, -4000],' newline ...
    '          "altitude_m": 4000,' newline ...
    '          "_note": "West to east, crosses T2 at (0,-35000) at t~40s"' newline ...
    '        },' newline ...
    '        {' newline ...
    '          "behavior": "crossing",' newline ...
    '          "speed_kmh": 800,' newline ...
    '          "start_pos": [0, -50000, -4000],' newline ...
    '          "end_pos": [0, -20000, -4000],' newline ...
    '          "altitude_m": 4000,' newline ...
    '          "_note": "South to north, SAME ALTITUDE as T1, co-located at t~40s"' newline ...
    '        },' newline ...
    '        {' newline ...
    '          "behavior": "s_maneuver",' newline ...
    '          "speed_kmh": 800,' newline ...
    '          "start_pos": [-8000, -30000, -4000],' newline ...
    '          "turn_rate_dps": 2,' newline ...
    '          "altitude_m": 4000,' newline ...
    '          "_note": "S-maneuver near crossing zone, adds data association ambiguity"' newline ...
    '        }' newline ...
    '      ]' newline ...
    '    }' newline];

    % Find insertion point: before the final two closing braces
    % The catalog ends with:  \n  }\n}\n
    % We need to insert after the last scenario's closing brace
    % Find "default_wedge_degraded" end block (last scenario before closing)
    lastScenEnd = strfind(txt, '"default_wedge_degraded"');
    if isempty(lastScenEnd)
        % Try finding the very end of the scenarios object
        % Look for the pattern: last '}' before the final '}'
        fprintf('  WARNING: Could not find default_wedge_degraded. Trying end-of-file insertion.\n');
    end
    
    % Strategy: find the last occurrence of "    }" followed by newlines and "  }" and "}"
    % This is the closing of the last scenario, then scenarios object, then root object
    endPattern = sprintf('      ]\n    }\n  }\n}');
    endIdx = strfind(txt, endPattern);
    if ~isempty(endIdx)
        insertPoint = endIdx(end) + length('      ]') + length(sprintf('\n    }'));
        before = txt(1:insertPoint);
        after = txt(insertPoint+1:end);
        txt = [before, newScenarios, after];
        
        fid = fopen(catPath, 'w');
        fprintf(fid, '%s', txt);
        fclose(fid);
        
        % Validate
        try
            jsondecode(txt);
            fprintf('  JSON validation: PASSED\n');
        catch ME
            fprintf('  WARNING: JSON validation FAILED: %s\n', ME.message);
            fprintf('  You may need to fix the catalog manually.\n');
        end
        
        fprintf('\n  ADDED: demo_ideal     — PSR+PAR, 3 targets, clean env\n');
        fprintf('  ADDED: demo_degraded  — PSR+PAR, 3 targets, env effects ON\n');
    else
        fprintf('  ERROR: Could not find insertion point in catalog.\n');
        fprintf('  Try adding manually to scenario_catalog.json.\n');
    end
end

% Clear any stale caches
for f = ["demo_ideal.mat", "demo_degraded.mat"]
    cf = fullfile(root, 'cache', f);
    if isfile(cf); delete(cf); fprintf('  Cleared cache: %s\n', f); end
end

fprintf('\nTo run the demo pair:\n');
fprintf('  addpath("scripts");\n');
fprintf('  runSingleScenario("demo_ideal")      %% clean — should be CLEAN\n');
fprintf('  runSingleScenario("demo_degraded")    %% env on — swaps expected\n');
