%% applyTerrainFix.m — Two targeted edits to show terrain across full plot
% Run from adeptus-rainyday-tracking root:
%   run('scripts/applyTerrainFix.m')

root = fileparts(fileparts(mfilename('fullpath')));

%% FIX 1: runSingleScenario.m — pass terrainGrid to dataLog
rssPath = fullfile(root, 'scripts', 'runSingleScenario.m');
txt = fileread(rssPath);
if contains(txt, 'dataLog.TerrainGrid')
    fprintf('[FIX 1] Already patched.\n');
else
    anchor = '    %% Scan check';
    insertion = [...
        '    %% Pass terrain grid to dataLog for 3D plot visualization' newline ...
        '    if isfield(config, ''terrainGrid'') && ~isempty(config.terrainGrid)' newline ...
        '        dataLog.TerrainGrid = config.terrainGrid;' newline ...
        '    end' newline newline ...
        '    %% Scan check'];
    txt = strrep(txt, anchor, insertion);
    fid = fopen(rssPath, 'w'); fprintf(fid, '%s', txt); fclose(fid);
    fprintf('[FIX 1] runSingleScenario.m — TerrainGrid pass-through added.\n');
end

%% FIX 2: runTracker.m — expand ROI to terrain bounds + cap altitude
rtPath = fullfile(root, 'src', '+trackbench', '+tracking', 'runTracker.m');
txt = fileread(rtPath);
if contains(txt, 'Expand ROI to include terrain')
    fprintf('[FIX 2] Already patched.\n');
else
    % The unique anchor is the last line before the function closes
    anchor = '        roi.zMin = min(roi.zMin, -500);  % show a bit below ground level';
    replacement = [anchor newline ...
        '    end' newline ...
        newline ...
        '    %% Expand ROI to include terrain grid so mountains fill the entire plot' newline ...
        '    if isfield(dataLog, ''TerrainGrid'') && ~isempty(dataLog.TerrainGrid)' newline ...
        '        tg = dataLog.TerrainGrid;' newline ...
        '        if isfield(tg, ''boundary'') && numel(tg.boundary) >= 4' newline ...
        '            bnd = tg.boundary;' newline ...
        '            roi.xMin = min(roi.xMin, bnd(1));' newline ...
        '            roi.xMax = max(roi.xMax, bnd(2));' newline ...
        '            roi.yMin = min(roi.yMin, bnd(3));' newline ...
        '            roi.yMax = max(roi.yMax, bnd(4));' newline ...
        '        elseif isfield(tg, ''X'')' newline ...
        '            roi.xMin = min(roi.xMin, min(tg.X(:)));' newline ...
        '            roi.xMax = max(roi.xMax, max(tg.X(:)));' newline ...
        '            roi.yMin = min(roi.yMin, min(tg.Y(:)));' newline ...
        '            roi.yMax = max(roi.yMax, max(tg.Y(:)));' newline ...
        '        end' newline ...
        '    end' newline ...
        newline ...
        '    %% Cap altitude axis — PSR elevation noise stretches Z to 60km+' newline ...
        '    roi.zMax = min(max(roi.zMax, 8000), 15000);'];
    
    % Also need to remove the old "    end\nend" that follows the anchor
    % The old pattern is: anchor + \n + "    end\n" + "end\n"
    oldBlock = [anchor newline '    end' newline 'end'];
    newBlock = [replacement newline 'end'];
    
    if contains(txt, oldBlock)
        txt = strrep(txt, oldBlock, newBlock);
        fid = fopen(rtPath, 'w'); fprintf(fid, '%s', txt); fclose(fid);
        fprintf('[FIX 2] runTracker.m — ROI expanded to terrain bounds, altitude capped.\n');
    else
        fprintf('[FIX 2] WARNING: Could not find exact anchor in runTracker.m.\n');
        fprintf('  Looking for: "%s"\n', anchor);
        % Try to find partial match
        if contains(txt, 'roi.zMin = min(roi.zMin')
            fprintf('  Found partial match — the file structure may differ.\n');
        end
    end
end

% Clear caches
for f = ["demo_ideal.mat", "demo_degraded.mat"]
    cf = fullfile(root, 'cache', f);
    if isfile(cf); delete(cf); fprintf('Cleared: %s\n', f); end
end

fprintf('\nDone. Run:  runSingleScenario("demo_ideal")\n');
fprintf('Expected: Mountains fill the entire ±130km plot area.\n');
fprintf('          Z axis capped at 15km (no more 60km outlier dots).\n');
