function buildModularConfig()
%buildModularConfig  Create the full modular config directory structure.
%
%  Run ONCE to set up the sandbox config folders. Creates:
%    config/runs/           — Run files (top-level, pass to runSingleScenario)
%    config/sensors/<TYPE>/ — One folder per sensor type (default + template + my_)
%    config/targets/<TYPE>/ — One folder per target behavior
%    config/terrain/<TYPE>/ — One folder per terrain type
%    config/trackers/<TYPE>/— One folder per tracker algorithm
%
%  USAGE
%    cd to adeptus-rainyday-tracking root, then:
%    addpath('scripts');
%    buildModularConfig
%
%  Existing files are NOT overwritten. Safe to re-run.

root = fileparts(fileparts(mfilename('fullpath')));
configDir = fullfile(root, 'config');
fprintf('\n[BUILD] Creating modular config structure in:\n  %s\n\n', configDir);

%% ========================================================================
%  RUNS — top-level files that reference all other components
%% ========================================================================
runsDir = fullfile(configDir, 'runs');
mkd(runsDir);

writeIfNew(fullfile(runsDir, 'dasr_baseline.json'), prettyJson(struct( ...
    'description', 'DASR baseline: PSR+SSR, two gentle-turn targets, rural terrain, clear weather', ...
    'sensors', {{'PSR/default_PSR', 'SSR/default_SSR'}}, ...
    'targets', 'gentle_turn/default_gentle_turn', ...
    'terrain', 'rural/default_rural', ...
    'trackers', {{'GNN/default_GNN', 'JPDA/default_JPDA'}}, ...
    'degradation', struct('enabled', false, 'type', 'rain'), ...
    'platforms', struct('placeholder',0), ...
    'output', struct('show_visuals',true,'animate_visuals',true, ...
        'save_results',true,'print_diagnostics',true,'results_directory','results') ...
)));

writeIfNew(fullfile(runsDir, 'demo_mountain.json'), prettyJson(struct( ...
    'description', 'Demo: PSR, 5 crossing targets, mountain terrain, clear weather (Boeing demo)', ...
    'sensors', {{'PSR/default_PSR'}}, ...
    'targets', 'crossing_5way/default_crossing_5way', ...
    'terrain', 'mountain/default_mountain', ...
    'trackers', {{'GNN/default_GNN', 'JPDA/default_JPDA'}}, ...
    'degradation', struct('enabled', false, 'type', 'rain'), ...
    'platforms', struct('placeholder',0), ...
    'output', struct('show_visuals',true,'animate_visuals',true, ...
        'save_results',true,'print_diagnostics',true,'results_directory','results') ...
)));

writeIfNew(fullfile(runsDir, 'fighter_intercept.json'), prettyJson(struct( ...
    'description', 'Fighter intercept: AESA+FLIR on aircraft, 2 bogeys, mountain terrain', ...
    'sensors', {{'AESA/default_AESA', 'FLIR/default_FLIR'}}, ...
    'targets', 'head_on/default_head_on', ...
    'terrain', 'mountain/default_mountain', ...
    'trackers', {{'GNN/default_GNN'}}, ...
    'degradation', struct('enabled', false, 'type', 'rain'), ...
    'platforms', struct('aircraft', struct( ...
        'start_pos', [0 0 -10000], 'heading_deg', 180, 'speed_kmh', 900)), ...
    'output', struct('show_visuals',true,'animate_visuals',true, ...
        'save_results',true,'print_diagnostics',true,'results_directory','results') ...
)));

writeIfNew(fullfile(runsDir, 'dasr_storm.json'), prettyJson(struct( ...
    'description', 'DASR in heavy rain: PSR+SSR, mountain terrain, storm degradation', ...
    'sensors', {{'PSR/default_PSR', 'SSR/default_SSR'}}, ...
    'targets', 'gentle_turn/default_gentle_turn', ...
    'terrain', 'mountain/default_mountain', ...
    'trackers', {{'GNN/default_GNN', 'JPDA/default_JPDA'}}, ...
    'degradation', struct('enabled', true, 'type', 'heavy_rain'), ...
    'platforms', struct('placeholder',0), ...
    'output', struct('show_visuals',true,'animate_visuals',true, ...
        'save_results',true,'print_diagnostics',true,'results_directory','results') ...
)));

writeIfNew(fullfile(runsDir, 'my_run.json'), prettyJson(struct( ...
    'description', 'YOUR DESCRIPTION HERE', ...
    'sensors', {{'PSR/default_PSR'}}, ...
    'targets', 'gentle_turn/default_gentle_turn', ...
    'terrain', 'rural/default_rural', ...
    'trackers', {{'GNN/default_GNN'}}, ...
    'degradation', struct('enabled', false, 'type', 'rain'), ...
    'platforms', struct('placeholder',0), ...
    'output', struct('show_visuals',true,'animate_visuals',true, ...
        'save_results',true,'print_diagnostics',true,'results_directory','results') ...
)));

% Template with full documentation (written as raw JSON since MATLAB
% struct doesn't support _-prefixed field names)
writeIfNew(fullfile(runsDir, 'run_template.json'), [...
'{' newline ...
'  "INSTRUCTIONS": [' newline ...
'    "1. Copy this file → config/runs/my_run.json",' newline ...
'    "2. Fill in sensor, target, terrain, tracker references",' newline ...
'    "3. Run: runSingleScenario(''my_run'')",' newline ...
'    "",' newline ...
'    "SENSORS: paths relative to config/sensors/. One file per sensor.",' newline ...
'    "TARGETS: path relative to config/targets/. Defines target behaviors + duration.",' newline ...
'    "TERRAIN: path relative to config/terrain/. Defines environment + terrain type.",' newline ...
'    "TRACKERS: paths relative to config/trackers/. Each defines tracker + filter + params.",' newline ...
'    "DEGRADATION: Weather effects. enabled=true activates rain.",' newline ...
'    "PLATFORMS: Only for moving sensor platforms (aircraft, ship). Omit for ground radar."' newline ...
'  ],' newline ...
'  "description": "MY SCENARIO DESCRIPTION",' newline ...
'  "sensors": ["PSR/default_PSR", "SSR/default_SSR"],' newline ...
'  "targets": "crossing_pair/default_crossing_pair",' newline ...
'  "terrain": "mountain/default_mountain",' newline ...
'  "trackers": ["GNN/default_GNN"],' newline ...
'  "degradation": { "enabled": false, "type": "rain" },' newline ...
'  "platforms": {},' newline ...
'  "output": {' newline ...
'    "show_visuals": true,' newline ...
'    "animate_visuals": true,' newline ...
'    "save_results": true,' newline ...
'    "print_diagnostics": true,' newline ...
'    "results_directory": "results"' newline ...
'  }' newline ...
'}']);

% README for runs folder
writeIfNew(fullfile(runsDir, 'README.md'), [...
'# Run Files' newline newline ...
'Each .json here defines a **complete simulation**.' newline ...
'Pass the filename (no .json) to runSingleScenario:' newline newline ...
'```matlab' newline ...
'runSingleScenario("dasr_baseline")    %% PSR+SSR, rural, GNN+JPDA' newline ...
'runSingleScenario("demo_mountain")    %% Boeing demo: 5 targets, mountain' newline ...
'runSingleScenario("my_run")           %% Your custom run' newline ...
'```' newline newline ...
'## Format' newline ...
'- **sensors**: list of sensor files from `config/sensors/<TYPE>/<file>`' newline ...
'- **targets**: target file from `config/targets/<pattern>/<file>`' newline ...
'- **terrain**: terrain file from `config/terrain/<type>/<file>`' newline ...
'- **trackers**: list of tracker files from `config/trackers/<TYPE>/<file>`' newline ...
'- **degradation**: `{ "enabled": true/false, "type": "rain" }`' newline ...
'- **platforms**: moving platforms (aircraft, ship). Omit `placeholder` field for no platforms.' newline ...
'- **output**: visuals, save, diagnostics' newline newline ...
'See `run_template.json` for a fully documented example.' newline]);

fprintf('[BUILD] Runs: %d files\n', 7);

%% ========================================================================
%  SENSORS — one folder per type, 3 files each
%% ========================================================================
sensorTypes = {'PSR','SSR','AESA','PAR','TWS','FIRE_CONTROL','ARSR','IRST','FLIR','MARITIME'};

sensorDefaults = struct();
sensorDefaults.PSR = struct('name','Primary Search Radar (DASR)','type','PSR','platform','tower', ...
    'params',struct('rpm',12.5,'fov',[1.4 30],'tilt',2,'pd',0.9,'far',1e-6, ...
        'rangeLimits',[0 111120],'rangeRes',93,'mountingLoc',[0 0 -15]));
sensorDefaults.SSR = struct('name','Secondary Surveillance Radar (MSSR/IFF)','type','SSR','platform','tower', ...
    'params',struct('rpm',12.5,'fov',[1.4 10],'tilt',2,'pd',0.99,'far',1e-7, ...
        'rangeLimits',[0 222240],'rangeRes',100,'refRCS',20,'mountingLoc',[0 0 -15]));
sensorDefaults.AESA = struct('name','AESA Fighter Radar','type','AESA','platform','aircraft', ...
    'params',struct('sector',[-60 60],'rangeLimits',[0 300000],'pd',0.85,'far',1e-6,'mountingLoc',[0 0 0]));
sensorDefaults.PAR = struct('name','Precision Approach Radar','type','PAR','platform','tower', ...
    'params',struct('sector',[170 190],'rangeLimits',[0 37040],'pd',0.95,'far',1e-7,'mountingLoc',[0 0 -10]));
sensorDefaults.TWS = struct('name','Track-While-Scan Phased Array','type','TWS','platform','tower', ...
    'params',struct('sector',[-60 60],'rangeLimits',[0 200000],'pd',0.9,'far',1e-6,'mountingLoc',[0 0 -20]));
sensorDefaults.FIRE_CONTROL = struct('name','Fire Control Radar','type','FIRE_CONTROL','platform','tower', ...
    'params',struct('sector',[-5 5],'rangeLimits',[0 150000],'pd',0.98,'far',1e-8,'mountingLoc',[0 0 -15]));
sensorDefaults.ARSR = struct('name','Air Route Surveillance Radar','type','ARSR','platform','tower', ...
    'params',struct('rpm',5,'fov',[1.4 40],'tilt',3,'pd',0.8,'far',1e-6, ...
        'rangeLimits',[0 463000],'rangeRes',200,'mountingLoc',[0 0 -30]));
sensorDefaults.IRST = struct('name','IR Search and Track','type','IRST','platform','tower', ...
    'params',struct('fov',[360 20],'rangeLimits',[0 100000],'pd',0.7,'mountingLoc',[0 0 -10]));
sensorDefaults.FLIR = struct('name','Forward-Looking Infrared','type','FLIR','platform','aircraft', ...
    'params',struct('sector',[-30 30],'rangeLimits',[0 30000],'pd',0.75,'mountingLoc',[0 0 0]));
sensorDefaults.MARITIME = struct('name','Maritime Surface Search Radar','type','MARITIME','platform','ship', ...
    'params',struct('rpm',25,'fov',[1.0 25],'tilt',0,'pd',0.85,'far',1e-5, ...
        'rangeLimits',[0 74000],'rangeRes',50,'mountingLoc',[0 0 -20]));

% Parameter documentation per sensor type (written into template files)
sensorDocs = struct();
sensorDocs.PSR = [...
    '"PARAM_DOCS": {' newline ...
    '    "rpm": "Rotation rate (RPM). DASR=12.5, ASR=15. Determines scan period.",' newline ...
    '    "fov": "[azimuth_deg, elevation_deg]. Wider az = more coverage per step.",' newline ...
    '    "tilt": "Antenna tilt (deg). Positive = up. Adjusts elevation center.",' newline ...
    '    "pd": "Detection probability (0-1). 0.9 typical for PSR.",' newline ...
    '    "far": "False alarm rate. 1e-6 typical. Lower = fewer ghost detections.",' newline ...
    '    "rangeLimits": "[min_m, max_m]. PSR=60nm (111120m). Max detection range.",' newline ...
    '    "rangeRes": "Range resolution (m). 93m typical. Smaller = better discrimination.",' newline ...
    '    "mountingLoc": "[x,y,z] NED offset from platform. z=-15 means 15m above ground."' newline ...
    '  }'];
sensorDocs.SSR = [...
    '"PARAM_DOCS": {' newline ...
    '    "rpm": "Must match co-located PSR for synchronized scanning.",' newline ...
    '    "pd": "0.99 — SSR uses cooperative transponder, very reliable.",' newline ...
    '    "far": "1e-7 — very low, transponder replies are discrete.",' newline ...
    '    "rangeLimits": "120nm — transponder has own TX, longer range than PSR.",' newline ...
    '    "refRCS": "Reference RCS (m^2). SSR uses transponder, not skin return."' newline ...
    '  }'];
sensorDocs.AESA = [...
    '"PARAM_DOCS": {' newline ...
    '    "sector": "[minAz, maxAz] electronic scan limits. ±60 typical for fighter.",' newline ...
    '    "rangeLimits": "300km. Airborne radar, high power.",' newline ...
    '    "pd": "0.85 — lower than ground due to airborne clutter.",' newline ...
    '    "mountingLoc": "Nose-mounted: [0,0,0]. Requires aircraft platform in run file."' newline ...
    '  }'];
sensorDocs.PAR = [...
    '"PARAM_DOCS": {' newline ...
    '    "sector": "[minAz, maxAz] pointing down runway. 170-190 = ±10deg of south.",' newline ...
    '    "rangeLimits": "20nm. Short range, high accuracy for final approach.",' newline ...
    '    "pd": "0.95 — high rate needed for precision guidance."' newline ...
    '  }'];
sensorDocs.TWS = sensorDocs.AESA;
sensorDocs.FIRE_CONTROL = [...
    '"PARAM_DOCS": {' newline ...
    '    "sector": "Very narrow (±5deg). Pencil beam tracks single target.",' newline ...
    '    "rangeLimits": "150km. Dedicated tracking, high power density.",' newline ...
    '    "pd": "0.98 — highest accuracy. Narrow beam = high gain.",' newline ...
    '    "far": "1e-8 — extremely low for weapons guidance."' newline ...
    '  }'];
sensorDocs.ARSR = [...
    '"PARAM_DOCS": {' newline ...
    '    "rpm": "5 RPM = 12s per rotation. Slow scan, long range.",' newline ...
    '    "rangeLimits": "250nm (463km). En-route surveillance.",' newline ...
    '    "pd": "0.8 — lower at extreme range is expected."' newline ...
    '  }'];
sensorDocs.IRST = [...
    '"PARAM_DOCS": {' newline ...
    '    "fov": "360deg azimuth. Passive sensor — no RF emission.",' newline ...
    '    "rangeLimits": "100km. Depends on target IR signature.",' newline ...
    '    "pd": "0.7 — depends on thermal contrast. Less affected by rain than radar."' newline ...
    '  }'];
sensorDocs.FLIR = [...
    '"PARAM_DOCS": {' newline ...
    '    "sector": "±30deg forward from aircraft nose.",' newline ...
    '    "rangeLimits": "30km. Short range, bearing-only. Complements AESA.",' newline ...
    '    "pd": "0.75 — passive IR."' newline ...
    '  }'];
sensorDocs.MARITIME = [...
    '"PARAM_DOCS": {' newline ...
    '    "rpm": "25 RPM — fast scan for surface contacts.",' newline ...
    '    "rangeLimits": "40nm. X-band surface search.",' newline ...
    '    "far": "1e-5 — higher due to sea clutter.",' newline ...
    '    "mountingLoc": "Ship mast: z=-20 = 20m above waterline."' newline ...
    '  }'];

for i = 1:numel(sensorTypes)
    sType = sensorTypes{i};
    sDir = fullfile(configDir, 'sensors', sType);
    mkd(sDir);

    defJson = prettyJson(sensorDefaults.(sType));

    % default — works out of box
    writeIfNew(fullfile(sDir, sprintf('default_%s.json', sType)), defJson);

    % template — same values + docs
    docs = sensorDocs.(sType);
    tmplJson = strrep(defJson, '}', sprintf(',\n  "INSTRUCTIONS": "Copy this file, rename it, edit params. Reference as: sensors/[%s/my_%s]",\n  %s\n}', sType, sType, docs));
    writeIfNew(fullfile(sDir, sprintf('%s_template.json', sType)), tmplJson);

    % my_ — user copy
    writeIfNew(fullfile(sDir, sprintf('my_%s.json', sType)), defJson);

    fprintf('[BUILD] Sensor: %s/ (3 files)\n', sType);
end

%% ========================================================================
%  TARGETS — one folder per behavior pattern
%% ========================================================================
targetDir = fullfile(configDir, 'targets');
mkd(targetDir);

% gentle_turn
mkd(fullfile(targetDir, 'gentle_turn'));
gt = struct('description','Two targets with gradual heading changes','duration_s',50, ...
    'targets',{{struct('behavior','gentle_turn','speed_kmh',900,'start_pos',[-2000 -20000 -3000],'altitude_m',3000), ...
                struct('behavior','gentle_turn','speed_kmh',700,'start_pos',[2000 -19000 -3500],'altitude_m',3500)}});
writeIfNew(fullfile(targetDir,'gentle_turn','default_gentle_turn.json'), prettyJson(gt));
writeIfNew(fullfile(targetDir,'gentle_turn','my_gentle_turn.json'), prettyJson(gt));
writeTargetTemplate(fullfile(targetDir,'gentle_turn','gentle_turn_template.json'), 'gentle_turn', ...
    'Gradual heading change. No extra fields needed beyond speed/position.');

% crossing_pair
mkd(fullfile(targetDir, 'crossing_pair'));
cp = struct('description','Two targets crossing at same altitude — track swap test','duration_s',60, ...
    'targets',{{struct('behavior','crossing','speed_kmh',800,'start_pos',[-20000 -30000 -5000],'end_pos',[20000 -30000 -5000],'altitude_m',5000), ...
                struct('behavior','crossing','speed_kmh',800,'start_pos',[0 -50000 -5000],'end_pos',[0 -10000 -5000],'altitude_m',5000)}});
writeIfNew(fullfile(targetDir,'crossing_pair','default_crossing_pair.json'), prettyJson(cp));
writeIfNew(fullfile(targetDir,'crossing_pair','my_crossing_pair.json'), prettyJson(cp));
writeTargetTemplate(fullfile(targetDir,'crossing_pair','crossing_pair_template.json'), 'crossing', ...
    'Straight line from start_pos to end_pos. Requires end_pos. Use pairs at same altitude for swap tests.');

% crossing_5way (Boeing demo)
mkd(fullfile(targetDir, 'crossing_5way'));
c5 = struct('description','5 targets: 2 crossing pairs + 1 S-maneuver (Boeing demo)','duration_s',90, ...
    'targets',{{ ...
        struct('behavior','crossing','speed_kmh',850,'start_pos',[-30000 -35000 -6000],'end_pos',[30000 -35000 -6000],'altitude_m',6000), ...
        struct('behavior','crossing','speed_kmh',800,'start_pos',[0 -55000 -6000],'end_pos',[0 -15000 -6000],'altitude_m',6000), ...
        struct('behavior','crossing','speed_kmh',750,'start_pos',[-20000 -25000 -6000],'end_pos',[20000 -45000 -6000],'altitude_m',6000), ...
        struct('behavior','crossing','speed_kmh',780,'start_pos',[15000 -25000 -6000],'end_pos',[-15000 -45000 -6000],'altitude_m',6000), ...
        struct('behavior','s_maneuver','speed_kmh',800,'start_pos',[-8000 -30000 -6000],'turn_rate_dps',2,'altitude_m',6000) ...
    }});
writeIfNew(fullfile(targetDir,'crossing_5way','default_crossing_5way.json'), prettyJson(c5));
writeIfNew(fullfile(targetDir,'crossing_5way','my_crossing_5way.json'), prettyJson(c5));
writeTargetTemplate(fullfile(targetDir,'crossing_5way','crossing_5way_template.json'), 'crossing+s_maneuver', ...
    'Boeing demo scenario. 5 targets at same altitude create multiple swap opportunities.');

% s_maneuver
mkd(fullfile(targetDir, 's_maneuver'));
sm = struct('description','Single target with aggressive S-maneuver — IMM vs CV test','duration_s',60, ...
    'targets',{{struct('behavior','s_maneuver','speed_kmh',900,'start_pos',[-5000 -20000 -3000],'turn_rate_dps',3,'altitude_m',3000)}});
writeIfNew(fullfile(targetDir,'s_maneuver','default_s_maneuver.json'), prettyJson(sm));
writeIfNew(fullfile(targetDir,'s_maneuver','my_s_maneuver.json'), prettyJson(sm));
writeTargetTemplate(fullfile(targetDir,'s_maneuver','s_maneuver_template.json'), 's_maneuver', ...
    'S-shaped evasive path. turn_rate_dps sets aggressiveness (2-5 typical). heading_deg optional.');

% head_on
mkd(fullfile(targetDir, 'head_on'));
ho = struct('description','Two targets approaching head-on — identity maintenance test','duration_s',40, ...
    'targets',{{struct('behavior','constant_velocity','speed_kmh',900,'start_pos',[-10000 -20000 -3000],'heading_deg',90,'altitude_m',3000), ...
                struct('behavior','constant_velocity','speed_kmh',900,'start_pos',[10000 -20000 -3000],'heading_deg',270,'altitude_m',3000)}});
writeIfNew(fullfile(targetDir,'head_on','default_head_on.json'), prettyJson(ho));
writeIfNew(fullfile(targetDir,'head_on','my_head_on.json'), prettyJson(ho));
writeTargetTemplate(fullfile(targetDir,'head_on','head_on_template.json'), 'constant_velocity', ...
    'Opposing headings (90 vs 270). heading_deg: 0=north, 90=east, 180=south, 270=west.');

% approach
mkd(fullfile(targetDir, 'approach'));
ap = struct('description','Two aircraft on landing approach — descending to runway','duration_s',90, ...
    'targets',{{struct('behavior','approach','speed_kmh',280,'start_pos',[0 -30000 -3000],'end_pos',[0 -500 -50],'altitude_m',3000), ...
                struct('behavior','approach','speed_kmh',260,'start_pos',[3000 -25000 -2500],'end_pos',[0 -500 -80],'altitude_m',2500)}});
writeIfNew(fullfile(targetDir,'approach','default_approach.json'), prettyJson(ap));
writeIfNew(fullfile(targetDir,'approach','my_approach.json'), prettyJson(ap));
writeTargetTemplate(fullfile(targetDir,'approach','approach_template.json'), 'approach', ...
    'Straight-in descending path. end_pos should be near runway threshold (z near 0).');

% orbit
mkd(fullfile(targetDir, 'orbit'));
ob = struct('description','Target in circular holding pattern','duration_s',120, ...
    'targets',{{struct('behavior','orbit','speed_kmh',600,'start_pos',[0 -25000 -4000],'orbit_radius_m',4000,'altitude_m',4000)}});
writeIfNew(fullfile(targetDir,'orbit','default_orbit.json'), prettyJson(ob));
writeIfNew(fullfile(targetDir,'orbit','my_orbit.json'), prettyJson(ob));
writeTargetTemplate(fullfile(targetDir,'orbit','orbit_template.json'), 'orbit', ...
    'Circular path around start_pos. orbit_radius_m sets circle size (3000-5000 typical).');

% high_density
mkd(fullfile(targetDir, 'high_density'));
hd = struct('description','5 targets with mixed behaviors — data association stress test','duration_s',60, ...
    'targets',{{ ...
        struct('behavior','constant_velocity','speed_kmh',900,'start_pos',[-3000 -22000 -3000],'heading_deg',45,'altitude_m',3000), ...
        struct('behavior','constant_velocity','speed_kmh',800,'start_pos',[2000 -18000 -3500],'heading_deg',200,'altitude_m',3500), ...
        struct('behavior','gentle_turn','speed_kmh',700,'start_pos',[0 -20000 -2800],'altitude_m',2800), ...
        struct('behavior','s_maneuver','speed_kmh',850,'start_pos',[-1000 -21000 -3200],'altitude_m',3200), ...
        struct('behavior','orbit','speed_kmh',600,'start_pos',[1000 -19500 -4000],'orbit_radius_m',3000,'altitude_m',4000) ...
    }});
writeIfNew(fullfile(targetDir,'high_density','default_high_density.json'), prettyJson(hd));
writeIfNew(fullfile(targetDir,'high_density','my_high_density.json'), prettyJson(hd));
writeTargetTemplate(fullfile(targetDir,'high_density','high_density_template.json'), 'mixed', ...
    '5 different behaviors near each other. Tests data association under ambiguity.');

fprintf('[BUILD] Targets: 8 folders\n');

%% ========================================================================
%  TERRAIN — one folder per type
%% ========================================================================
terrainDir = fullfile(configDir, 'terrain');
mkd(terrainDir);

terrainTypes = {'water','rural','urban','mountain','desert'};
terrainDescs = {'Flat sea level. No effects. Open ocean / coastal.', ...
    'Rolling farmland, 80m peaks, light clutter.', ...
    'City terrain, building clusters 150m, moderate clutter.', ...
    'Mountain ridges and peaks 2000m, heavy occlusion.', ...
    'Gentle dunes 40m, light clutter.'};
terrainOcc   = [false true true true true];
terrainMask  = [false true true true true];
terrainClut  = [false true true true true];
terrainDens  = [0 0.3 0.6 0.5 0.2];

for i = 1:numel(terrainTypes)
    tt = terrainTypes{i};
    tDir = fullfile(terrainDir, tt);
    mkd(tDir);

    tDef = struct('description', terrainDescs{i}, ...
        'terrain_type', tt, 'terrain_scale', 1.0, ...
        'terrain_occlusion', terrainOcc(i), 'horizon_masking', terrainMask(i), ...
        'ground_clutter', terrainClut(i), 'propagation_model', false, ...
        'clutter_density', terrainDens(i), 'refraction_factor', 1.333);

    defJson = prettyJson(tDef);
    writeIfNew(fullfile(tDir, sprintf('default_%s.json', tt)), defJson);
    writeIfNew(fullfile(tDir, sprintf('my_%s.json', tt)), defJson);

    % Template with docs
    tmplJson = strrep(defJson, '}', [...
        ',' newline ...
        '  "INSTRUCTIONS": "Copy this file, rename, edit. Reference as: terrain/' tt '/my_' tt '",' newline ...
        '  "PARAM_DOCS": {' newline ...
        '    "terrain_type": "water|rural|urban|mountain|desert — drives heightmap generation",' newline ...
        '    "terrain_scale": "Elevation multiplier. 2.0=double height, 0.5=half.",' newline ...
        '    "terrain_occlusion": "true/false — LOS blocked by terrain surface.",' newline ...
        '    "horizon_masking": "true/false — Earth curvature hides low targets.",' newline ...
        '    "ground_clutter": "true/false — terrain-dependent false radar returns.",' newline ...
        '    "propagation_model": "true/false — multipath lobing via radarvcd. Slow but realistic.",' newline ...
        '    "clutter_density": "0-1. 0=none, 1=heavy.",' newline ...
        '    "refraction_factor": "4/3 Earth model. 1.0=optical, >1.33=ducting."' newline ...
        '  }' newline ...
        '}']);
    writeIfNew(fullfile(tDir, sprintf('%s_template.json', tt)), tmplJson);

    fprintf('[BUILD] Terrain: %s/ (3 files)\n', tt);
end

%% ========================================================================
%  TRACKERS — one folder per algorithm
%% ========================================================================
trackerDir = fullfile(configDir, 'trackers');
mkd(trackerDir);

globalParams = struct('max_num_tracks',500,'volume',1e9,'beta',1e-14, ...
    'detection_probability',struct('ideal',0.9,'degraded',0.7));
filterParams = struct('init_speed_kmh',900,'imm_transition_prob',0.97, ...
    'scale_accel_horz',30,'scale_omega_dot',30);

% GNN
mkd(fullfile(trackerDir, 'GNN'));
gnn = struct('description','Global Nearest Neighbor — fast, deterministic', ...
    'tracker_type','GNN','filter_model','IMM', ...
    'params',struct('gate',45,'far_gnn',1e-6,'confirm_threshold',20,'delete_threshold',-5, ...
        'gate_jpda',45,'far_jpda',1e-6,'far_mht',1e-6,'beta_jpda',1e-14, ...
        'time_tolerance_jpda',0.05,'num_tracks_jpda',500, ...
        'tomht_threshold_multiplier',[0.2 1 1],'max_branches',5), ...
    'global',globalParams,'filter',filterParams);
writeIfNew(fullfile(trackerDir,'GNN','default_GNN.json'), prettyJson(gnn));
writeIfNew(fullfile(trackerDir,'GNN','my_GNN.json'), prettyJson(gnn));
writeTrackerTemplate(fullfile(trackerDir,'GNN','GNN_template.json'), 'GNN');

% JPDA
mkd(fullfile(trackerDir, 'JPDA'));
jpda = gnn; jpda.description = 'Joint Probabilistic Data Association — soft assignment, real-time';
jpda.tracker_type = 'JPDA'; jpda.filter_model = 'IMM';
writeIfNew(fullfile(trackerDir,'JPDA','default_JPDA.json'), prettyJson(jpda));
writeIfNew(fullfile(trackerDir,'JPDA','my_JPDA.json'), prettyJson(jpda));
writeTrackerTemplate(fullfile(trackerDir,'JPDA','JPDA_template.json'), 'JPDA');

% TOMHT
mkd(fullfile(trackerDir, 'TOMHT'));
tomht = gnn; tomht.description = 'Track-Oriented Multi-Hypothesis — most accurate, slower';
tomht.tracker_type = 'TOMHT'; tomht.filter_model = 'IMM';
writeIfNew(fullfile(trackerDir,'TOMHT','default_TOMHT.json'), prettyJson(tomht));
writeIfNew(fullfile(trackerDir,'TOMHT','my_TOMHT.json'), prettyJson(tomht));
writeTrackerTemplate(fullfile(trackerDir,'TOMHT','TOMHT_template.json'), 'TOMHT');

fprintf('[BUILD] Trackers: GNN/ JPDA/ TOMHT/ (3 files each)\n');

%% ========================================================================
%  DONE
%% ========================================================================
fprintf('\n');
fprintf('╔══════════════════════════════════════════════════════════╗\n');
fprintf('║           MODULAR CONFIG STRUCTURE CREATED              ║\n');
fprintf('╠══════════════════════════════════════════════════════════╣\n');
fprintf('║  Run files:  config/runs/         (pass to runSingle)   ║\n');
fprintf('║  Sensors:    config/sensors/<TYPE>/                     ║\n');
fprintf('║  Targets:    config/targets/<PATTERN>/                  ║\n');
fprintf('║  Terrain:    config/terrain/<TYPE>/                     ║\n');
fprintf('║  Trackers:   config/trackers/<TYPE>/                    ║\n');
fprintf('╠══════════════════════════════════════════════════════════╣\n');
fprintf('║  Each folder has:                                       ║\n');
fprintf('║    default_<n>.json  — premade, works out of box        ║\n');
fprintf('║    <n>_template.json — documented, explains each param  ║\n');
fprintf('║    my_<n>.json       — your copy to customize           ║\n');
fprintf('╠══════════════════════════════════════════════════════════╣\n');
fprintf('║  NEXT: runSingleScenario("dasr_baseline")               ║\n');
fprintf('╚══════════════════════════════════════════════════════════╝\n\n');

end % main


%% ========================================================================
%  HELPERS
%% ========================================================================
function mkd(d)
    if ~exist(d, 'dir'); mkdir(d); end
end

function writeIfNew(filepath, content)
    if exist(filepath, 'file')
        return;  % never overwrite
    end
    fid = fopen(filepath, 'w', 'n', 'UTF-8');
    fprintf(fid, '%s', content);
    fclose(fid);
end

function txt = prettyJson(s)
    txt = jsonencode(s, 'PrettyPrint', true);
    % Strip placeholder workaround (MATLAB can't encode empty struct as {})
    txt = regexprep(txt, '\{\s*"placeholder":\s*0\s*\}', '{}');
end

function writeTargetTemplate(filepath, behaviorType, behaviorDoc)
    if exist(filepath, 'file'); return; end
    txt = [...
        '{' newline ...
        '  "INSTRUCTIONS": [' newline ...
        '    "Copy this file, rename it, edit the targets array.",' newline ...
        '    "Reference in a run file as: targets/<folder>/my_<name>",' newline ...
        '    "Each target needs: behavior, speed_kmh, start_pos, altitude_m.",' newline ...
        '    "Extra fields depend on behavior (see PARAM_DOCS)."' newline ...
        '  ],' newline ...
        '  "PARAM_DOCS": {' newline ...
        '    "behavior": "' behaviorType '  — ' behaviorDoc '",' newline ...
        '    "speed_kmh": "Target speed in km/h. 200-2000 for aircraft, 20-60 for ships.",' newline ...
        '    "start_pos": "[x, y, z] NED meters. z is negative (altitude above ground).",' newline ...
        '    "altitude_m": "Altitude ASL in meters. Overrides start_pos(3).",' newline ...
        '    "heading_deg": "(constant_velocity/head_on) 0=N, 90=E, 180=S, 270=W.",' newline ...
        '    "end_pos": "(crossing/approach) [x,y,z] destination point.",' newline ...
        '    "turn_rate_dps": "(s_maneuver) Turn rate deg/s. 2-5 typical.",' newline ...
        '    "orbit_radius_m": "(orbit) Circle radius meters. 3000-5000 typical."' newline ...
        '  },' newline ...
        '  "description": "YOUR DESCRIPTION",' newline ...
        '  "duration_s": 60,' newline ...
        '  "targets": [' newline ...
        '    {' newline ...
        '      "behavior": "' behaviorType '",' newline ...
        '      "speed_kmh": 900,' newline ...
        '      "start_pos": [-5000, -20000, -3000],' newline ...
        '      "altitude_m": 3000' newline ...
        '    }' newline ...
        '  ]' newline ...
        '}'];
    fid = fopen(filepath, 'w', 'n', 'UTF-8');
    fprintf(fid, '%s', txt);
    fclose(fid);
end

function writeTrackerTemplate(filepath, trackerType)
    if exist(filepath, 'file'); return; end
    txt = [...
        '{' newline ...
        '  "INSTRUCTIONS": [' newline ...
        '    "Copy this file, rename it, tune parameters.",' newline ...
        '    "Reference in a run file as: trackers/' trackerType '/my_' trackerType '"' newline ...
        '  ],' newline ...
        '  "PARAM_DOCS": {' newline ...
        '    "tracker_type": "GNN | JPDA | TOMHT",' newline ...
        '    "filter_model": "CV = straight line assumption. IMM = handles turns (recommended).",' newline ...
        '    "gate": "Association gate. Larger=more permissive. 30-120 typical.",' newline ...
        '    "far_gnn": "False alarm rate for GNN score logic. 1e-6 typical.",' newline ...
        '    "far_jpda": "False alarm rate for JPDA. 1e-6 typical.",' newline ...
        '    "far_mht": "False alarm rate for TOMHT. 1e-6 typical.",' newline ...
        '    "confirm_threshold": "Score to confirm a track. Higher=slower but fewer false tracks.",' newline ...
        '    "delete_threshold": "Score below which track is deleted. -3 to -10 typical.",' newline ...
        '    "tomht_threshold_multiplier": "[coarse med fine] x gate. TOMHT 3-level assignment.",' newline ...
        '    "max_branches": "Max TOMHT hypotheses per track. 3-8 typical.",' newline ...
        '    "global.max_num_tracks": "Max simultaneous tracks. 500 default.",' newline ...
        '    "global.volume": "Surveillance volume (m^3). 1e9 typical.",' newline ...
        '    "global.beta": "New-target density. 1e-14 typical.",' newline ...
        '    "filter.init_speed_kmh": "Expected target speed for filter init.",' newline ...
        '    "filter.imm_transition_prob": "IMM model switching probability. 0.97 default.",' newline ...
        '    "filter.scale_accel_horz": "Process noise acceleration (m/s^2). 30 default."' newline ...
        '  }' newline ...
        '}'];
    fid = fopen(filepath, 'w', 'n', 'UTF-8');
    fprintf(fid, '%s', txt);
    fclose(fid);
end