%% fixRunTracker.m — Replace normalizeDetectionDimensions with HasVelocity fix
% Run from adeptus-rainyday-tracking root:
%   run('scripts/fixRunTracker.m')

root = fileparts(fileparts(mfilename('fullpath')));
rtPath = fullfile(root, 'src', '+trackbench', '+tracking', 'runTracker.m');
fprintf('Patching: %s\n', rtPath);

rtTxt = fileread(rtPath);

% Check if already has the HasVelocity fix
if contains(rtTxt, 'HasVelocity')
    fprintf('Already has HasVelocity fix. Skipping.\n');
    return;
end

% Find and replace the old normalizeDetectionDimensions function
oldFunc = 'function detsOut = normalizeDetectionDimensions(detsIn)';
funcIdx = strfind(rtTxt, oldFunc);
if isempty(funcIdx)
    fprintf('ERROR: normalizeDetectionDimensions not found in runTracker.m\n');
    fprintf('Run patchLayeredDefense.m first to add the base normalization.\n');
    return;
end

% Remove everything from the old function definition to end of file
rtTxt = rtTxt(1:funcIdx(1)-1);

% Append the new, complete function with HasVelocity fix
newFunc = [...
'function detsOut = normalizeDetectionDimensions(detsIn)' newline ...
'%normalizeDetectionDimensions  Normalize all detections to 3-element position-only.' newline ...
'%' newline ...
'%  Multi-sensor scenarios produce mixed measurement sizes:' newline ...
'%    PSR/IRST:       3 elements [x, y, z]' newline ...
'%    Fire control/TWS/AESA: 6 elements [x, y, z, vx, vy, vz]' newline ...
'%' newline ...
'%  When initcvekf(detection) initializes a track, it reads' newline ...
'%  MeasurementParameters.HasVelocity to decide the measurement function.' newline ...
'%  If HasVelocity=true, the filter expects 6-element measurements forever.' newline ...
'%  Later 3-element detections then crash with:' newline ...
'%    "MeasurementJacobianFcn must be a matrix of size 3 x 6"' newline ...
'%' newline ...
'%  Fix: strip ALL detections to position-only by:' newline ...
'%    1. Truncate Measurement to first 3 elements' newline ...
'%    2. Truncate MeasurementNoise to 3x3' newline ...
'%    3. Set HasVelocity=false in MeasurementParameters (critical!)' newline ...
newline ...
'    if isempty(detsIn); detsOut = detsIn; return; end' newline ...
'    detsOut = detsIn;' newline ...
'    for ii = 1:numel(detsOut)' newline ...
'        det = detsOut{ii};' newline ...
'        nMeas = numel(det.Measurement);' newline ...
'        if nMeas > 3' newline ...
'            % 1. Strip measurement to position only' newline ...
'            det.Measurement = det.Measurement(1:3);' newline ...
newline ...
'            % 2. Trim MeasurementNoise to 3x3 (position block)' newline ...
'            R = det.MeasurementNoise;' newline ...
'            if ~isscalar(R) && size(R,1) >= 3 && size(R,2) >= 3' newline ...
'                det.MeasurementNoise = R(1:3, 1:3);' newline ...
'            end' newline ...
newline ...
'            % 3. Fix MeasurementParameters — tell filter this is position-only' newline ...
'            %    Without this, initcvekf reads HasVelocity=true and builds a' newline ...
'            %    6-element measurement function that crashes on 3-element data.' newline ...
'            mp = det.MeasurementParameters;' newline ...
'            if isstruct(mp)' newline ...
'                for m = 1:numel(mp)' newline ...
'                    if isfield(mp(m), ''HasVelocity'')' newline ...
'                        mp(m).HasVelocity = false;' newline ...
'                    end' newline ...
'                end' newline ...
'                det.MeasurementParameters = mp;' newline ...
'            elseif iscell(mp)' newline ...
'                for m = 1:numel(mp)' newline ...
'                    if isstruct(mp{m}) && isfield(mp{m}, ''HasVelocity'')' newline ...
'                        mp{m}.HasVelocity = false;' newline ...
'                        det.MeasurementParameters = mp;' newline ...
'                    end' newline ...
'                end' newline ...
'            end' newline ...
newline ...
'            detsOut{ii} = det;' newline ...
'        end' newline ...
'    end' newline ...
'end' newline];

rtTxt = [strtrim(rtTxt), newline, newline, newFunc];

fid = fopen(rtPath, 'w');
fprintf(fid, '%s', rtTxt);
fclose(fid);

fprintf('DONE — normalizeDetectionDimensions now sets HasVelocity=false.\n');
fprintf('This fixes the "MeasurementJacobianFcn must be 3x6" crash.\n\n');

% Also clear stale cache
cacheFile = fullfile(root, 'cache', 'layered_defense.mat');
if isfile(cacheFile)
    delete(cacheFile);
    fprintf('Deleted stale cache: %s\n', cacheFile);
end

fprintf('\nNow run:\n  addpath("scripts");\n  runSingleScenario("layered_defense")\n');
