%% fixTerrainVisuals.m — Fix terrain coverage in tracker 3D plots
% Run from adeptus-rainyday-tracking root:
%   run('scripts/fixTerrainVisuals.m')
%
% TWO FIXES:
%   1. runSingleScenario.m — pass config.terrainGrid → dataLog.TerrainGrid
%      (was missing, so tracker plots never received the terrain data for ROI)
%   2. runTracker.m — expand computeDynamicROI to include terrain extent
%      (was only using target positions, clipping terrain at plot edges)
%      Also caps altitude axis at 15km to avoid PSR elevation noise stretching Z

root = fileparts(fileparts(mfilename('fullpath')));

%% Fix 1: runSingleScenario.m — pass terrain grid to dataLog
rssPath = fullfile(root, 'scripts', 'runSingleScenario.m');
fprintf('Patching: %s\n', rssPath);
rssTxt = fileread(rssPath);

if contains(rssTxt, 'dataLog.TerrainGrid')
    fprintf('  Already has TerrainGrid pass-through. Skipping.\n');
else
    oldBlock = '    end' + newline + newline + '    %% Scan check';
    newBlock = [...
        '    end' newline ...
        newline ...
        '    % Pass terrain grid to dataLog for 3D tracker plot visualization.' newline ...
        '    % loadScenario stores it in config.terrainGrid; the tracker plots need' newline ...
        '    % it in dataLog.TerrainGrid to draw terrain and expand the ROI.' newline ...
        '    if isfield(config, ''terrainGrid'') && ~isempty(config.terrainGrid)' newline ...
        '        dataLog.TerrainGrid = config.terrainGrid;' newline ...
        '    end' newline ...
        newline ...
        '    %% Scan check'];
    
    % Find the right "end" block (after the HasIFF check, before Scan check)
    if contains(rssTxt, oldBlock)
        rssTxt = strrep(rssTxt, oldBlock, newBlock);
        fid = fopen(rssPath, 'w'); fprintf(fid, '%s', rssTxt); fclose(fid);
        fprintf('  DONE — TerrainGrid now passed from config to dataLog.\n');
    else
        fprintf('  WARNING: Could not find insertion point. Manual edit needed.\n');
        fprintf('  Add after dataLog creation: dataLog.TerrainGrid = config.terrainGrid;\n');
    end
end

%% Fix 2: runTracker.m — expand ROI to include terrain extent
rtPath = fullfile(root, 'src', '+trackbench', '+tracking', 'runTracker.m');
fprintf('Patching: %s\n', rtPath);
rtTxt = fileread(rtPath);

if contains(rtTxt, 'TerrainGrid') && contains(rtTxt, 'maxDisplayAlt')
    fprintf('  Already has terrain ROI expansion. Skipping.\n');
else
    % Find the old computeDynamicROI function end
    oldEnd = '        roi.zMin = min(roi.zMin, -500);  % show a bit below ground level' + newline + '    end' + newline + 'end';
    
    newEnd = [...
        '        roi.zMin = min(roi.zMin, -500);  % show a bit below ground level' newline ...
        '    end' newline ...
        newline ...
        '    % Expand ROI to include terrain grid extent so mountains fill the plot' newline ...
        '    if isfield(dataLog, ''TerrainGrid'') && ~isempty(dataLog.TerrainGrid)' newline ...
        '        tg = dataLog.TerrainGrid;' newline ...
        '        if isfield(tg, ''boundary'') && numel(tg.boundary) >= 4' newline ...
        '            bnd = tg.boundary;  % [xMin xMax yMin yMax]' newline ...
        '            roi.xMin = min(roi.xMin, bnd(1));' newline ...
        '            roi.xMax = max(roi.xMax, bnd(2));' newline ...
        '            roi.yMin = min(roi.yMin, bnd(3));' newline ...
        '            roi.yMax = max(roi.yMax, bnd(4));' newline ...
        '        elseif isfield(tg, ''X'')' newline ...
        '            roi.xMin = min(roi.xMin, min(tg.X(:)));' newline ...
        '            roi.xMax = max(roi.xMax, max(tg.X(:)));' newline ...
        '            roi.yMin = min(roi.yMin, min(tg.Y(:)));' newline ...
        '            roi.yMax = max(roi.yMax, max(tg.Y(:)));' newline ...
        '        end' newline ...
        '    end' newline ...
        newline ...
        '    % Cap altitude axis at reasonable display range.' newline ...
        '    % PSR elevation noise can produce detections at 60km+ which' newline ...
        '    % stretches Z axis and makes tracks/terrain invisible.' newline ...
        '    maxDisplayAlt = max(roi.zMax, 8000);' newline ...
        '    maxDisplayAlt = min(maxDisplayAlt, 15000);' newline ...
        '    roi.zMax = maxDisplayAlt;' newline ...
        'end'];
    
    if contains(rtTxt, oldEnd)
        rtTxt = strrep(rtTxt, oldEnd, newEnd);
        fid = fopen(rtPath, 'w'); fprintf(fid, '%s', rtTxt); fclose(fid);
        fprintf('  DONE — ROI now includes terrain bounds + altitude capped at 15km.\n');
    else
        fprintf('  WARNING: Could not find computeDynamicROI end block.\n');
        fprintf('  Manual edit needed in computeDynamicROI function.\n');
    end
end

% Clear caches
for f = ["demo_ideal.mat", "demo_degraded.mat"]
    cf = fullfile(root, 'cache', f);
    if isfile(cf); delete(cf); fprintf('Cleared: %s\n', f); end
end

fprintf('\nBoth fixes applied. Run:\n');
fprintf('  runSingleScenario("demo_ideal")\n');
fprintf('\nExpected: Mountains visible across entire ±130km plot area.\n');
fprintf('          Altitude axis capped at 15km (no more 60km outliers).\n');
