%% fixTerrainCoverage.m — Expand terrain grid to fill full radar coverage area
% Run from adeptus-rainyday-tracking root:
%   run('scripts/fixTerrainCoverage.m')
%
% WHAT: Changes computeScenarioBounds in loadScenario.m to:
%   1. Center terrain on radar origin (0,0) instead of target centroid
%   2. Use 130km minimum halfSpan (covers PSR 60nm range)
%   3. Compute extent from farthest platform, not just midpoint
%
% WHY: Terrain only covered ~60km around targets. Now fills the full
%      3D plot so mountains are visible across the entire radar coverage.

root = fileparts(fileparts(mfilename('fullpath')));
lsPath = fullfile(root, 'src', '+trackbench', '+scenario', 'loadScenario.m');
fprintf('Patching: %s\n', lsPath);
txt = fileread(lsPath);

% Check if already patched
if contains(txt, 'CENTERED ON ORIGIN')
    fprintf('Already patched. Skipping.\n');
    return;
end

oldFunc = [...
    'function bounds = computeScenarioBounds(scenario, duration)' newline ...
    '%computeScenarioBounds  Estimate XY extents from all platform trajectories.' newline ...
    '%  Returns [xMin xMax; yMin yMax] with 20% margin. Used to size the terrain' newline ...
    '%  grid so it covers the full scenario footprint.'];

newFunc = [...
    'function bounds = computeScenarioBounds(scenario, duration)' newline ...
    '%computeScenarioBounds  Estimate XY extents from all platform trajectories.' newline ...
    '%  Returns [xMin xMax; yMin yMax] with margin. Used to size the terrain' newline ...
    '%  grid so it covers the full radar coverage area.' newline ...
    '%  CENTERED ON ORIGIN (radar location) so terrain fills the 3D plot.'];

if ~contains(txt, oldFunc)
    fprintf('ERROR: Could not find computeScenarioBounds header.\n');
    return;
end

txt = strrep(txt, oldFunc, newFunc);

% Replace the bounds computation logic
oldCalc = [...
    '    xMin = min(allPos(:,1));' newline ...
    '    xMax = max(allPos(:,1));' newline ...
    '    yMin = min(allPos(:,2));' newline ...
    '    yMax = max(allPos(:,2));' newline ...
    '    ' newline ...
    '    % Ensure minimum span (at least 60km in each direction from center)' newline ...
    '    cx = (xMin + xMax) / 2;' newline ...
    '    cy = (yMin + yMax) / 2;' newline ...
    '    halfSpan = max([abs(xMax-xMin)/2, abs(yMax-yMin)/2, 60000]);' newline ...
    '    ' newline ...
    '    % Add 20% margin' newline ...
    '    halfSpan = halfSpan * 1.2;' newline ...
    '    ' newline ...
    '    bounds = [cx-halfSpan, cx+halfSpan; cy-halfSpan, cy+halfSpan];'];

newCalc = [...
    '    % Find the farthest point from origin in any direction' newline ...
    '    maxExtent = max(vecnorm(allPos(:,1:2), 2, 2));' newline ...
    '    ' newline ...
    '    % Ensure minimum span covers the maximum sensor range (130km for PSR)' newline ...
    '    halfSpan = max(maxExtent * 1.15, 130000);' newline ...
    '    ' newline ...
    '    % Center on origin (radar location) so terrain fills the full plot' newline ...
    '    bounds = [-halfSpan, halfSpan; -halfSpan, halfSpan];'];

if contains(txt, oldCalc)
    txt = strrep(txt, oldCalc, newCalc);
    fid = fopen(lsPath, 'w');
    fprintf(fid, '%s', txt);
    fclose(fid);
    fprintf('DONE — Terrain now covers ±130km centered on radar origin.\n');
    fprintf('Mountains will fill the entire 3D plot.\n\n');
else
    fprintf('ERROR: Could not find bounds computation block.\n');
    fprintf('The function may have been modified already.\n');
end

% Clear stale caches
for f = ["demo_ideal.mat", "demo_degraded.mat"]
    cf = fullfile(root, 'cache', f);
    if isfile(cf); delete(cf); fprintf('Cleared cache: %s\n', f); end
end

fprintf('\nRun:  runSingleScenario("demo_ideal")\n');
