%% patchRunTracker.m — Apply TOMHT measurement normalization fix
% Run this once from the adeptus-rainyday-tracking root:
%   run('scripts/patchRunTracker.m')
%
% WHAT IT DOES:
%   1. Inserts normalizeDetectionDimensions() call after detection cell normalization
%   2. Appends normalizeDetectionDimensions() helper function at end of file
%   This fixes the TOMHT "Expected MeasurementNoise to be a scalar or 6-by-6 matrix"
%   crash caused by mixed 3/6-element detections from multi-sensor scenarios.

targetFile = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
    'src', '+trackbench', '+tracking', 'runTracker.m');

fprintf('Patching: %s\n', targetFile);
assert(isfile(targetFile), 'runTracker.m not found at expected path');

% Read existing file
txt = fileread(targetFile);

% Check if already patched
if contains(txt, 'normalizeDetectionDimensions')
    fprintf('[PATCH] Already applied — normalizeDetectionDimensions exists. Skipping.\n');
    return;
end

%% PATCH 1: Insert normalization call after detection cell array creation
insertAfter = '    scanCells = num2cell(scanBuffer(:));';
insertBlock = sprintf([...
    '    end\n' ...
    '\n' ...
    '    %%%% -------- Normalize mixed measurement dimensions --------\n' ...
    '    %%%% Multi-sensor scenarios may produce detections with different measurement\n' ...
    '    %%%% sizes (e.g., PSR gives 3-element [x,y,z], fire control/TWS gives\n' ...
    '    %%%% 6-element [x,y,z,vx,vy,vz]). All MATLAB trackers (especially TOMHT)\n' ...
    '    %%%% require consistent measurement dimensions across a scan.\n' ...
    '    %%%%\n' ...
    '    %%%% Fix: strip velocity components from any detection with >3 elements,\n' ...
    '    %%%% keeping position-only. This is safe because the Kalman filter estimates\n' ...
    '    %%%% velocity from position history anyway, and it prevents the TOMHT\n' ...
    '    %%%% "Expected MeasurementNoise to be a scalar or 6-by-6 matrix" crash.\n' ...
    '    scanCells = normalizeDetectionDimensions(scanCells);\n']);

% Replace "end" + old comment with "end" + normalization + old comment
oldBlock = sprintf('    end\n\n    %%%% No pre-filtering of detections.');
newBlock = sprintf('%s\n    %%%% No pre-filtering of detections.', insertBlock);
txt = strrep(txt, oldBlock, newBlock);

%% PATCH 2: Append normalizeDetectionDimensions function at end of file
appendFunc = sprintf(['\n\n' ...
    'function detsOut = normalizeDetectionDimensions(detsIn)\n' ...
    '%%%%normalizeDetectionDimensions  Ensure all detections have 3-element measurements.\n' ...
    '%%%%\n' ...
    '%%%% Multi-sensor scenarios produce detections with mixed measurement sizes:\n' ...
    '%%%%   - PSR/SSR/IRST: 3 elements [x, y, z]\n' ...
    '%%%%   - Fire control/TWS/AESA: 6 elements [x, y, z, vx, vy, vz]\n' ...
    '%%%%\n' ...
    '%%%% TOMHT (and other trackers) crash when filter dimensions don''t match\n' ...
    '%%%% the detection dimensions. Fix: normalize everything to position-only.\n' ...
    '%%%%\n' ...
    '%%%% For each detection with >3 measurement elements:\n' ...
    '%%%%   1. Keep only first 3 elements of Measurement\n' ...
    '%%%%   2. Keep only upper-left 3x3 of MeasurementNoise\n' ...
    '\n' ...
    '    if isempty(detsIn)\n' ...
    '        detsOut = detsIn;\n' ...
    '        return;\n' ...
    '    end\n' ...
    '\n' ...
    '    detsOut = detsIn;\n' ...
    '    for ii = 1:numel(detsOut)\n' ...
    '        det = detsOut{ii};\n' ...
    '        nMeas = numel(det.Measurement);\n' ...
    '        if nMeas > 3\n' ...
    '            det.Measurement = det.Measurement(1:3);\n' ...
    '            R = det.MeasurementNoise;\n' ...
    '            if ~isscalar(R) && size(R,1) >= 3 && size(R,2) >= 3\n' ...
    '                det.MeasurementNoise = R(1:3, 1:3);\n' ...
    '            end\n' ...
    '            detsOut{ii} = det;\n' ...
    '        end\n' ...
    '    end\n' ...
    'end\n']);

txt = [strtrim(txt), appendFunc];

%% Write patched file
fid = fopen(targetFile, 'w');
fprintf(fid, '%s', txt);
fclose(fid);
fprintf('[PATCH] Success — runTracker.m patched with normalizeDetectionDimensions.\n');
fprintf('[PATCH] TOMHT will now work with mixed-dimension multi-sensor scenarios.\n');
