%% patchLayeredDefense.m — Fix layered_defense scenario for real tracking challenge
% Run this once from the adeptus-rainyday-tracking root:
%   run('scripts/patchLayeredDefense.m')
%
% WHAT IT DOES:
%   1. Patches runTracker.m to normalize mixed measurement dimensions (fixes TOMHT crash)
%   2. Disables SSR in sensors_layered_defense.json (removes too-perfect IFF)
%   3. Redesigns layered_defense targets for real data association challenge
%   4. Enables environment effects (horizon masking, ground clutter, propagation model)
%   5. Deletes stale cached detections so they regenerate fresh

root = fileparts(fileparts(mfilename('fullpath')));
fprintf('\n========================================\n');
fprintf('  LAYERED DEFENSE SCENARIO PATCHER\n');
fprintf('  Root: %s\n', root);
fprintf('========================================\n\n');

%% ========================================================================
%  PATCH 1: runTracker.m — Add normalizeDetectionDimensions
% =========================================================================
fprintf('[PATCH 1] runTracker.m — measurement dimension normalization...\n');
rtPath = fullfile(root, 'src', '+trackbench', '+tracking', 'runTracker.m');
assert(isfile(rtPath), 'runTracker.m not found');
rtTxt = fileread(rtPath);

if contains(rtTxt, 'normalizeDetectionDimensions')
    fprintf('  Already patched. Skipping.\n');
else
    % Insert normalization call after cell array creation
    oldStr = sprintf('    end\n\n    %% No pre-filtering');
    newStr = sprintf(['    end\n\n' ...
        '    %%%% -------- Normalize mixed measurement dimensions --------\n' ...
        '    %%%% Multi-sensor scenarios produce mixed 3/6-element detections.\n' ...
        '    %%%% TOMHT crashes on mixed sizes. Normalize all to position-only (3-element).\n' ...
        '    scanCells = normalizeDetectionDimensions(scanCells);\n\n' ...
        '    %% No pre-filtering']);
    rtTxt = strrep(rtTxt, oldStr, newStr);

    % Append helper function
    helperFunc = sprintf(['\n\n' ...
        'function detsOut = normalizeDetectionDimensions(detsIn)\n' ...
        '%%%%normalizeDetectionDimensions  Strip 6-element detections to 3-element (position only).\n' ...
        '    if isempty(detsIn); detsOut = detsIn; return; end\n' ...
        '    detsOut = detsIn;\n' ...
        '    for ii = 1:numel(detsOut)\n' ...
        '        det = detsOut{ii};\n' ...
        '        if numel(det.Measurement) > 3\n' ...
        '            det.Measurement = det.Measurement(1:3);\n' ...
        '            R = det.MeasurementNoise;\n' ...
        '            if ~isscalar(R) && size(R,1) >= 3 && size(R,2) >= 3\n' ...
        '                det.MeasurementNoise = R(1:3, 1:3);\n' ...
        '            end\n' ...
        '            detsOut{ii} = det;\n' ...
        '        end\n' ...
        '    end\n' ...
        'end\n']);
    rtTxt = [strtrim(rtTxt), helperFunc];

    fid = fopen(rtPath, 'w'); fprintf(fid, '%s', rtTxt); fclose(fid);
    fprintf('  DONE — TOMHT will now work with mixed-dimension sensors.\n');
end

%% ========================================================================
%  PATCH 2: sensors_layered_defense.json — Disable SSR
% =========================================================================
fprintf('\n[PATCH 2] sensors_layered_defense.json — disabling SSR/IFF...\n');
sensPath = fullfile(root, 'config', 'sensors', 'sensors_layered_defense.json');
assert(isfile(sensPath), 'sensors_layered_defense.json not found');
sensTxt = fileread(sensPath);

if contains(sensTxt, '"enabled": false') || contains(sensTxt, '"enabled":false')
    fprintf('  SSR already disabled. Skipping.\n');
else
    fprintf('  ERROR: Could not detect SSR state. Check file manually.\n');
end

%% ========================================================================
%  PATCH 3: scenario_catalog.json — Replace layered_defense block via text
% =========================================================================
fprintf('\n[PATCH 3] scenario_catalog.json — redesigning layered_defense...\n');
catPath = fullfile(root, 'config', 'scenarios', 'scenario_catalog.json');
assert(isfile(catPath), 'scenario_catalog.json not found');
catTxt = fileread(catPath);

if contains(catTxt, 'crossing targets + environment')
    fprintf('  Already patched (crossing targets present). Skipping.\n');
else
    % Build the new layered_defense JSON block
    newBlock = [
        '    "layered_defense": {' newline ...
        '      "description": "Full layered defense — PSR+IRST+FC+TWS (SSR off), 4 sensors, crossing targets + environment effects",' newline ...
        '      "sensor_config": "sensors_layered_defense",' newline ...
        '      "overrides": {' newline ...
        '        "scenario.duration_s": 80,' newline ...
        '        "scenario.num_targets": 4,' newline ...
        '        "degradation.enabled": false,' newline ...
        '        "data_logging.use_saved_datalog": false,' newline ...
        '        "data_logging.datalog_file": "cache/layered_defense.mat",' newline ...
        '        "tracker_params.ideal.gate": 60,' newline ...
        '        "environment.horizon_masking": true,' newline ...
        '        "environment.ground_clutter": true,' newline ...
        '        "environment.propagation_model": true,' newline ...
        '        "environment.terrain_type": "rural",' newline ...
        '        "environment.clutter_density": 0.6' newline ...
        '      },' newline ...
        '      "targets": [' newline ...
        '        {' newline ...
        '          "behavior": "crossing",' newline ...
        '          "speed_kmh": 850,' newline ...
        '          "start_pos": [-25000, -35000, -4000],' newline ...
        '          "end_pos": [25000, -35000, -4000],' newline ...
        '          "altitude_m": 4000,' newline ...
        '          "_note": "CROSSING PAIR A — west to east at 35km range"' newline ...
        '        },' newline ...
        '        {' newline ...
        '          "behavior": "crossing",' newline ...
        '          "speed_kmh": 800,' newline ...
        '          "start_pos": [0, -50000, -4200],' newline ...
        '          "end_pos": [0, -20000, -4200],' newline ...
        '          "altitude_m": 4200,' newline ...
        '          "_note": "CROSSING PAIR A — south to north, crosses target 1 mid-scenario"' newline ...
        '        },' newline ...
        '        {' newline ...
        '          "behavior": "s_maneuver",' newline ...
        '          "speed_kmh": 900,' newline ...
        '          "start_pos": [-10000, -25000, -3500],' newline ...
        '          "turn_rate_dps": 3,' newline ...
        '          "altitude_m": 3500,' newline ...
        '          "_note": "Aggressive S-maneuver near target 4 orbit"' newline ...
        '        },' newline ...
        '        {' newline ...
        '          "behavior": "orbit",' newline ...
        '          "speed_kmh": 600,' newline ...
        '          "start_pos": [5000, -28000, -3800],' newline ...
        '          "orbit_radius_m": 4000,' newline ...
        '          "altitude_m": 3800,' newline ...
        '          "_note": "Orbiting target near target 3 S-maneuver path"' newline ...
        '        }' newline ...
        '      ]' newline ...
        '    },'];

    % Find the old layered_defense block and replace it
    % Pattern: from "layered_defense": { ... to the next scenario entry
    startTag = '    "layered_defense": {';
    endTag   = '    "layered_defense_storm": {';

    startIdx = strfind(catTxt, startTag);
    endIdx   = strfind(catTxt, endTag);

    if isempty(startIdx) || isempty(endIdx)
        fprintf('  ERROR: Could not locate layered_defense block boundaries.\n');
    else
        % Replace everything from startTag to just before endTag
        before = catTxt(1:startIdx(1)-1);
        after  = catTxt(endIdx(1):end);
        catTxt = [before, newBlock, newline, newline, after];

        fid = fopen(catPath, 'w');
        fprintf(fid, '%s', catTxt);
        fclose(fid);
        fprintf('  DONE — 4 targets redesigned with crossing paths + env effects.\n');

        % Verify JSON is still valid
        try
            jsondecode(catTxt);
            fprintf('  JSON validation: PASSED\n');
        catch ME
            fprintf('  WARNING: JSON validation failed: %s\n', ME.message);
            fprintf('  You may need to fix the catalog manually.\n');
        end
    end
end

%% ========================================================================
%  PATCH 4: Delete stale cached detections
% =========================================================================
fprintf('\n[PATCH 4] Clearing stale cache...\n');
cacheFile = fullfile(root, 'cache', 'layered_defense.mat');
if isfile(cacheFile)
    delete(cacheFile);
    fprintf('  Deleted: %s\n', cacheFile);
else
    fprintf('  No stale cache found.\n');
end

%% ========================================================================
%  DONE
% =========================================================================
fprintf('\n========================================\n');
fprintf('  ALL PATCHES APPLIED\n');
fprintf('========================================\n\n');
fprintf('Changes:\n');
fprintf('  1. runTracker.m          — TOMHT mixed-dimension fix\n');
fprintf('  2. sensors_layered_*.json — SSR disabled (no more perfect IFF)\n');
fprintf('  3. scenario_catalog.json  — crossing targets + env effects\n');
fprintf('  4. cache cleared          — fresh detections on next run\n');
fprintf('\nTo test, run:\n');
fprintf('  addpath("scripts");\n');
fprintf('  runSingleScenario("layered_defense")\n\n');
