%% updateDemoScenarios.m — Update demo_ideal and demo_degraded to use DASR + terrain
% Run from adeptus-rainyday-tracking root:
%   run('scripts/updateDemoScenarios.m')
%
% DEMO STORY:
%   Video 1 (demo_ideal):    DASR PSR+SSR, crossing targets, rural terrain VISIBLE,
%                             all environment effects OFF → trackers hold, CLEAN
%   Video 2 (demo_degraded): SAME DASR, SAME targets, SAME terrain,
%                             rain degradation ON + all environment effects ON
%                             → SSR Pd drops 0.99→0.5, clutter floods PSR,
%                             VCP masks detections → track swaps at crossing

root = fileparts(fileparts(mfilename('fullpath')));
catPath = fullfile(root, 'config', 'scenarios', 'scenario_catalog.json');
fprintf('Updating demo scenarios in: %s\n', catPath);
txt = fileread(catPath);

%% ========================================================================
%  REPLACE demo_ideal
% =========================================================================
newIdeal = [...
    '"demo_ideal": {' newline ...
    '      "description": "DEMO: DASR PSR+SSR fusion, 3 crossing targets, rural terrain, clean — baseline",' newline ...
    '      "sensor_config": "sensors_demo_dasr",' newline ...
    '      "overrides": {' newline ...
    '        "scenario.duration_s": 80,' newline ...
    '        "scenario.num_targets": 3,' newline ...
    '        "degradation.enabled": false,' newline ...
    '        "data_logging.use_saved_datalog": false,' newline ...
    '        "data_logging.datalog_file": "cache/demo_ideal.mat",' newline ...
    '        "tracker_params.ideal.gate": 80,' newline ...
    '        "environment.terrain_occlusion": false,' newline ...
    '        "environment.horizon_masking": false,' newline ...
    '        "environment.ground_clutter": false,' newline ...
    '        "environment.propagation_model": false,' newline ...
    '        "environment.terrain_type": "rural",' newline ...
    '        "environment.clutter_density": 0' newline ...
    '      },' newline ...
    '      "targets": [' newline ...
    '        {' newline ...
    '          "behavior": "crossing",' newline ...
    '          "speed_kmh": 850,' newline ...
    '          "start_pos": [-25000, -35000, -4000],' newline ...
    '          "end_pos": [25000, -35000, -4000],' newline ...
    '          "altitude_m": 4000,' newline ...
    '          "_note": "West to east, crosses T2 at (0,-35000) at t~40s"' newline ...
    '        },' newline ...
    '        {' newline ...
    '          "behavior": "crossing",' newline ...
    '          "speed_kmh": 800,' newline ...
    '          "start_pos": [0, -50000, -4000],' newline ...
    '          "end_pos": [0, -20000, -4000],' newline ...
    '          "altitude_m": 4000,' newline ...
    '          "_note": "South to north, SAME ALTITUDE as T1, co-located at t~40s"' newline ...
    '        },' newline ...
    '        {' newline ...
    '          "behavior": "s_maneuver",' newline ...
    '          "speed_kmh": 800,' newline ...
    '          "start_pos": [-8000, -30000, -4000],' newline ...
    '          "turn_rate_dps": 2,' newline ...
    '          "altitude_m": 4000,' newline ...
    '          "_note": "S-maneuver near crossing zone, same altitude"' newline ...
    '        }' newline ...
    '      ]' newline ...
    '    }'];

%% ========================================================================
%  REPLACE demo_degraded
% =========================================================================
newDegraded = [...
    '"demo_degraded": {' newline ...
    '      "description": "DEMO: DASR PSR+SSR fusion, SAME targets, rain + all environment effects ON — swaps expected",' newline ...
    '      "sensor_config": "sensors_demo_dasr",' newline ...
    '      "overrides": {' newline ...
    '        "scenario.duration_s": 80,' newline ...
    '        "scenario.num_targets": 3,' newline ...
    '        "degradation.enabled": true,' newline ...
    '        "degradation.type": "rain",' newline ...
    '        "data_logging.use_saved_datalog": false,' newline ...
    '        "data_logging.datalog_file": "cache/demo_degraded.mat",' newline ...
    '        "tracker_params.degraded.gate": 100,' newline ...
    '        "tracker_params.degraded.confirm_threshold": 12,' newline ...
    '        "tracker_params.degraded.delete_threshold": -5,' newline ...
    '        "tracker_global.detection_probability.degraded": 0.5,' newline ...
    '        "environment.terrain_occlusion": false,' newline ...
    '        "environment.horizon_masking": true,' newline ...
    '        "environment.ground_clutter": true,' newline ...
    '        "environment.propagation_model": true,' newline ...
    '        "environment.terrain_type": "rural",' newline ...
    '        "environment.clutter_density": 0.7' newline ...
    '      },' newline ...
    '      "targets": [' newline ...
    '        {' newline ...
    '          "behavior": "crossing",' newline ...
    '          "speed_kmh": 850,' newline ...
    '          "start_pos": [-25000, -35000, -4000],' newline ...
    '          "end_pos": [25000, -35000, -4000],' newline ...
    '          "altitude_m": 4000,' newline ...
    '          "_note": "West to east, crosses T2 at (0,-35000) at t~40s"' newline ...
    '        },' newline ...
    '        {' newline ...
    '          "behavior": "crossing",' newline ...
    '          "speed_kmh": 800,' newline ...
    '          "start_pos": [0, -50000, -4000],' newline ...
    '          "end_pos": [0, -20000, -4000],' newline ...
    '          "altitude_m": 4000,' newline ...
    '          "_note": "South to north, SAME ALTITUDE as T1, co-located at t~40s"' newline ...
    '        },' newline ...
    '        {' newline ...
    '          "behavior": "s_maneuver",' newline ...
    '          "speed_kmh": 800,' newline ...
    '          "start_pos": [-8000, -30000, -4000],' newline ...
    '          "turn_rate_dps": 2,' newline ...
    '          "altitude_m": 4000,' newline ...
    '          "_note": "S-maneuver near crossing zone, same altitude"' newline ...
    '        }' newline ...
    '      ]' newline ...
    '    }'];

%% ========================================================================
%  Apply replacements via text surgery
% =========================================================================
changed = false;

% --- Replace demo_ideal ---
idealStart = strfind(txt, '"demo_ideal"');
if ~isempty(idealStart)
    % Find the end of this scenario block (next scenario key or end of scenarios)
    afterIdeal = txt(idealStart(1):end);
    % Count braces to find matching close
    braceCount = 0; endIdx = 0;
    for c = 1:numel(afterIdeal)
        if afterIdeal(c) == '{'; braceCount = braceCount + 1; end
        if afterIdeal(c) == '}'; braceCount = braceCount - 1; end
        if braceCount == 0 && c > 1
            endIdx = c;
            break;
        end
    end
    if endIdx > 0
        absEnd = idealStart(1) + endIdx - 1;
        txt = [txt(1:idealStart(1)-1), newIdeal, txt(absEnd+1:end)];
        fprintf('  Replaced demo_ideal → DASR PSR+SSR, terrain=rural, env OFF\n');
        changed = true;
    end
end

% --- Replace demo_degraded ---
degradedStart = strfind(txt, '"demo_degraded"');
if ~isempty(degradedStart)
    afterDegraded = txt(degradedStart(1):end);
    braceCount = 0; endIdx = 0;
    for c = 1:numel(afterDegraded)
        if afterDegraded(c) == '{'; braceCount = braceCount + 1; end
        if afterDegraded(c) == '}'; braceCount = braceCount - 1; end
        if braceCount == 0 && c > 1
            endIdx = c;
            break;
        end
    end
    if endIdx > 0
        absEnd = degradedStart(1) + endIdx - 1;
        txt = [txt(1:degradedStart(1)-1), newDegraded, txt(absEnd+1:end)];
        fprintf('  Replaced demo_degraded → DASR PSR+SSR, rain, terrain=rural, env ON\n');
        changed = true;
    end
end

%% Write and validate
if changed
    fid = fopen(catPath, 'w');
    fprintf(fid, '%s', txt);
    fclose(fid);
    
    try
        jsondecode(fileread(catPath));
        fprintf('  JSON validation: PASSED\n');
    catch ME
        fprintf('  WARNING: JSON invalid: %s\n', ME.message);
    end
else
    fprintf('  No changes made — scenarios not found in catalog.\n');
end

% Clear stale caches
for f = ["demo_ideal.mat", "demo_degraded.mat"]
    cf = fullfile(root, 'cache', f);
    if isfile(cf); delete(cf); fprintf('  Cleared cache: %s\n', f); end
end

fprintf('\n========================================\n');
fprintf('  DEMO SCENARIOS UPDATED\n');
fprintf('========================================\n\n');
fprintf('  demo_ideal:\n');
fprintf('    Sensors  : DASR (PSR + SSR) — sensor fusion\n');
fprintf('    Targets  : 3 crossing at 4km, same altitude\n');
fprintf('    Terrain  : rural (visible in 3D plot)\n');
fprintf('    Weather  : CLEAR — no degradation, no env effects\n');
fprintf('    Expected : CLEAN across all trackers\n\n');
fprintf('  demo_degraded:\n');
fprintf('    Sensors  : DASR (PSR + SSR) — same\n');
fprintf('    Targets  : identical to ideal\n');
fprintf('    Terrain  : rural (same, visible)\n');
fprintf('    Weather  : RAIN — Pd drops 0.99→0.5 (SSR misses half)\n');
fprintf('    Effects  : horizon masking + ground clutter + VCP propagation\n');
fprintf('    Expected : SWAPS at crossing point (~t=40s)\n\n');
fprintf('Run:\n');
fprintf('  addpath("scripts");\n');
fprintf('  runSingleScenario("demo_ideal")      %% Video 1\n');
fprintf('  runSingleScenario("demo_degraded")    %% Video 2\n');
